### ISSUE TITLE
CSS classes do not work on Firefox

### ISSUE THREAD

**Issue by estacioneto** [danilowoz/react-content-loader#100]
## What did you do? 
I tried to make some reusable content loaders so they could be editable via CSS. It doesn't work on Firefox. To make my content loaders editable, I had to do [this](https://github.com/vtex-apps/store-components/blob/4942cc5c3b5db5c106bb6cb1bacc218238a01797/react/components/ProductName/index.js#L44-L49).

## What did you expect to happen?
I expected the Content Loader to be editable via CSS and work in all browsers.

## What happened actually?
It didn't show up. But, I saw [this](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect#Attributes) and the note says it's possible to work on SVG2.
I know it's not the latest release, but is there a way you could allow the SVG version to be editable? It would probably solve my issue completely.

[Here is sandbox so you can test it.](https://codesandbox.io/s/64l2yo05jr)

### Which versions of react-content-loader, and which browser are affected by this issue?
react: '^16.3.2'
react-content-loader: '^3.1.2'
Browser affected: Mozilla Firefox

**Comment by danilowoz** [comment]
Hey @estacioneto 
I really can't figure out a solution to this problem. It looks a Firefox bug instead in the React or this package. Also, your workaround looks great.

I'm going to close this issue, ok?
