### ISSUE TITLE
Option to remove view box

### ISSUE THREAD

**Issue by dogancana** [danilowoz/react-content-loader#107]
This is not a bug, but a question/discussion

I'm not sure if I'm using svg's properly but for having responsive Skeletons, I thought of disabling viewBox. And I did so by passing unexpected values to width/height. Then by skeleton loader was responsive in the way I want (more with in desktop, same height for rectangles)

1- Do you think that's correct approach for this kind of svgs?
2- If you answered yes/maybe, can we add an option to remove view box?

**Comment by danilowoz** [comment]
Hey @dogancana 
I'm not sure if it's a big deal removing the `viewBox`, because it controls how its contents are displayed (positions, unit, size). 

Can you send the loader? Maybe I can help you to reach what you want. 

Regards

**Comment by rerissondaniel** [comment]
@danilowoz 
I'm having this exact same issue. The viewbox wasnt working because we where passing its values in percentage, but we want to get rid of the warnings shown in console. I've tried to use unit values, but the loader loses its responsiveness :(

One of those loaders can be seen [here](https://github.com/vtex-apps/store-components/blob/61a68ef7317f4db983d2a92d937c6e97a557052a/react/components/ProductName/index.js#L37).

I didn't know if I should open a new issue or comment on this one.

**Comment by danilowoz** [comment]
Hey @rerissondaniel @dogancana, sorry for that

so, I just released a new version with a workaround, then please update to the v3.3.0 and take a look at this: https://github.com/danilowoz/react-content-loader/blob/master/stories/index.js#L114

Let me know if it solved your problem.
Thanks, take care

**Comment by magrinj** [comment]
@danilowoz Same problem happen on native for React-Native, `<Svg` can handle with and height as a percentage, but `viewBox` can't handle this percentage, in the code right there:
https://github.com/danilowoz/react-content-loader/blob/4c9f06184a138666eb5ecb14a7fd8e0450407856/src/native/Svg.tsx#L102
`width` and `height` are destructured, and passed to the native `Svg` component inside `viewBox` prop, and `width` and `height`, a solution should be to have separate props for `viewBox` and classic component `width`.
I can make a PR, if this solution looks good to you !

**Comment by danilowoz** [comment]
Hey @magrinj, thanks for getting in touch.

Actually width and height are not only used in `viewBox` but also in SVG mask. I guess you can reach what you want just using `style` for both platform, web and native. 

I know the properties name (width and height) seems a little trick, but its functions are clear in the documentation (https://github.com/danilowoz/react-content-loader#width-number) and it's extremely necessary to build the loading component.

So let me know if `style` works for you or please let me know how I can help you.

**Comment by magrinj** [comment]
@danilowoz Thanks for your answer, from what I've seen in the code of `Svg.tsx`, `width` and `height` props are set to `Rect`, `Svg` and `viewBox` prop of `Svg`.

`Rect` and `Svg` component can handle percentage with their prop `width` and `height`, but not in `viewBox` prop.

When I set a style to `ContentLoader` with `width: '100%'`, that's not working. 

If I set a `with="100%"` to `ContentLoader`, that's working but with a warning about `viewBox` because this one can't handle percentage.

Everything is working fine if I totally remove `viewBox` prop from `Svg`.

**Comment by danilowoz** [comment]
@magrinj do you mind to send me your loading and environment you are using?
Then I can take a look at it and think in a solution without any break changes

**Comment by magrinj** [comment]
@danilowoz No problem:

The code bellow is actually not working:

```javascript
// @flow
import React from 'react';
import {StyleSheet, View} from 'react-native';
import ContentLoader, {Rect, Circle} from 'react-content-loader/native';

import Colors from 'utils/colors';
import {spaceBetween} from 'utils/spacing';

type Props = {
  style?: any,
};

const ActivityLoading = ({style}: Props) => (
    <ContentLoader
      style={[styles.container, style]}
      height="123"
      speed={1}
      interval={0.1}
      primaryColor={Colors.LOADINGPRIMARY}
      secondaryColor={Colors.LOADINGSECONDARY}>
      <Circle cx="33" cy="34" r="23" />
      <Rect x="66" y="12" rx="4" ry="4" width="250" height="11" />
      <Rect x="66" y="26" rx="4" ry="4" width="100" height="11" />
      <Rect x="10" y="68" rx="4" ry="4" width="80%" height="11" />
      <Rect x="10" y="85" rx="4" ry="4" width="60%" height="11" />
      <Rect x="10" y="102" rx="4" ry="4" width="75%" height="11" />
    </ContentLoader>
);

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.BACKGROUNDLIGHTD,
    marginBottom: spaceBetween,
   width: '100%',
  },
});

export default ActivityLoading;
```

But if I remove in the library the viewBox and set it like that:

```javascript
// @flow
import React from 'react';
import {StyleSheet, View} from 'react-native';
import ContentLoader, {Rect, Circle} from 'react-content-loader/native';

import Colors from 'utils/colors';
import {spaceBetween} from 'utils/spacing';

type Props = {
  style?: any,
};

const ActivityLoading = ({style}: Props) => (
    <ContentLoader
      style={[styles.container, style]}
      width="100%"
      height="123"
      speed={1}
      interval={0.1}
      primaryColor={Colors.LOADINGPRIMARY}
      secondaryColor={Colors.LOADINGSECONDARY}>
      <Circle cx="33" cy="34" r="23" />
      <Rect x="66" y="12" rx="4" ry="4" width="250" height="11" />
      <Rect x="66" y="26" rx="4" ry="4" width="100" height="11" />
      <Rect x="10" y="68" rx="4" ry="4" width="80%" height="11" />
      <Rect x="10" y="85" rx="4" ry="4" width="60%" height="11" />
      <Rect x="10" y="102" rx="4" ry="4" width="75%" height="11" />
    </ContentLoader>
);

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.BACKGROUNDLIGHTD,
    marginBottom: spaceBetween,
  },
});

export default ActivityLoading;
```
 Everything is working fine

**Comment by danilowoz** [comment]
Hey @magrinj, I got your point and I was not able to reach what you want only using CSS.

I just was figuring out how to implement it without any break changes and change the API too much. So what about creating a new property called `noViewBox` or `removeViewBox` on both platforms (web and native)?

Let me know your thoughts about it

**Comment by magrinj** [comment]
Hey @danilowoz, thanks for your answer ! The pasted code above was used in a react-native app, you're speaking about CSS, so you try to reproduce it in a web app ?

A custom prop to disable the view box seems good to me as viewBox can't handle percentage

**Comment by danilowoz** [comment]
I tried on both platforms and when I said CSS I meant stylesheet in a general way.

Nice, so let's go ahead with this approach, do you want to take care of it? I kind of busy right now, maybe the next week I can handle it.

Thanks

**Comment by magrinj** [comment]
Ok, I understand !

I'm busy too this week, I'll try maybe next one if I can :)

**Comment by danilowoz** [comment]
Hey @magrinj, I just noticed a thing.

I was reading the documentation and I found [this](https://github.com/danilowoz/react-content-loader/blob/master/docs/props.mdx#viewbox-string). Don't judge me please, I didn't read the documentation of my own project hahaha

It quite makes sense, once I'm doing spreading of rest of properties [here](https://github.com/danilowoz/react-content-loader/blob/master/src/Svg.tsx#L41), then it will shift the old `viewBox` prop. On my tests, this approach works fine.

Let me know if it works for you

**Comment by magrinj** [comment]
Hey @danilowoz, Thanks a lot for your answer, you're totally fine !
It will works like a charm, thanks a lot, I didn't saw this props first time I used this library, sorry for that
