### ISSUE TITLE
Black layout issue while base-href is set on Safari/iOS  

### ISSUE THREAD

**Issue by gtabidze** [danilowoz/react-content-loader#109]
## What did you do? 
React content Loaders

## What did you expect to happen?
Expected to work for all browsers

## What happened actually?
Black layout issue while base-href is set on Safari/iOS. Somehow we found out that SVG url() doesn't work under  <base href="/"> in Safari/iOS. We removed <base href="/"> from page and issue solved.

### Which versions of react-content-loader, and which browser are affected by this issue?
Latest, Safari (Web/Mobile)

**Comment by danilowoz** [comment]
Thanks to sharing your solution :)
