### ISSUE TITLE
Accessibility - title/aria-labeledby

### ISSUE THREAD

**Issue by jmarceli** [danilowoz/react-content-loader#110]
Hi,
While writing tests I have a problem with querying react-content-loader components because there is no text/label which may allow for identifying them besides `<svg/>` tag.

While this problem is not so hard to solve using `getElementByTagName('svg')` in tests it makes me think that for screen readers etc. it might be much more difficult to tell the user what these SVG images are about.

Why don't we provide default `<title>Loading</title>` tag for each ContentLoader component? (and/or `aria-labeledby`)
This Loading text might be configurable using props if one would like to provide more info like "Loading avatar image".

What do you think about that?

**Comment by danilowoz** [comment]
Great! I'm going to work on

**Comment by endbay** [comment]
Is it possible to disable that feature? I really don't need this in my project. `ariaLabel` only accept String, it would be great if it could accept boolean false as well.

**Comment by danilowoz** [comment]
Hey @endbay, what kind of problem are you having? 
Actually, it doesn't change anything in loading, also it's a not required prop.

Thanks

**Comment by endbay** [comment]
I have design issue by that, if it's loading and you mouse over the loader, it shows the default chrome tooltip "loading interface". I know i can change the text, but i don't wan't any tooltip at all.

**Comment by danilowoz** [comment]
Humm I haven't noticed that a tooltip appears on hover... 
I'm going to work in a workaround about it 

Thanks

**Comment by gorilla-devs** [comment]
Any update on this? It's really annoying to see the popup

**Comment by danilowoz** [comment]
Release this fix in `v3.4.2`
From now the `ariaLabel` accepts a boolean which will remove the title and the `aria-label` attr

Let me know if it works
