### ISSUE TITLE
Is it possible to have content floating over the animation?

### ISSUE THREAD

**Issue by noamyg** [danilowoz/react-content-loader#121]
Hi,
First of all, I just wanted to say thanks! This component saved me so much time...

I'm trying to place a reCaptcha over the Instagram-style loader. The overall idea is to give users the impression that the content they're watching is bot-protected... while it is actually public 🤣

So, I have this:

![image](https://user-images.githubusercontent.com/34273570/49547742-3e89f900-f8ec-11e8-8d05-4069b132b4a8.png)

And I was wondering if I could get the reCaptcha floating over the animation (centered). I tried to implement it with <ContentLoader> without any success.

The code is:

```
<Recaptcha
	sitekey="XXXXX"
	render="explicit"
	verifyCallback={this.verifyRecaptcha}
	onloadCallback={this.onloadRecaptcha}
/>
{
	this.state.loadedDoc ?
		<object data={`${require(`../assets/docs/${this.state.loadedDoc.file}`)}#toolbar=0&navpanes=0&scrollbar=0&view=FitW`} type="application/pdf" className="embedded-document" style={{overflow:'hidden'}} width="100%" height="100%">
		</object> 
	: <Instagram />
}
```
My version is 3.4.1.

Thanks again!

**Comment by danilowoz** [comment]
Sure!
https://codesandbox.io/s/98v26pp9kr

Was that what you wanted?
