### ISSUE TITLE
RTL switch not working

### ISSUE THREAD

**Issue by adamgajzlerowicz** [danilowoz/react-content-loader#122]
I flipped the rtl flag on the component - seems that the navigation has changed, but the content stayed the same. Do I need to make my own RTL component? I thought it would switch around automatically.
I went to http://danilowoz.com/create-content-loader/ and switching RTL flag also does nothing.
Thanks

**Comment by adamgajzlerowicz** [comment]
Oh - I just re-read the docs. RTL only switches the animation. It would be cool if it actually switched the items around

**Comment by danilowoz** [comment]
Hey @adamgajzlerowicz 
Actually, you already can do it: https://codesandbox.io/s/l4k77664l7
But what it was missing is update the direction of animation, does make sense? 

Let me know if it's ok for you

**Comment by adamgajzlerowicz** [comment]
Hi

Not really - I am looking to switch loaders based on the locale - The language changes and LTR prop changes, so I made this:

```
const LoaderRTL = () => (
  <Fragment>
    <circle cx={`calc(100% - ${circleSize}px`} cy="23" r={circleSize} />
    <rect
      x={`calc(100% - ${sideMargin}px - ${lineWidthOne}%)`}
      y="0"
      rx="4"
      ry="4"
      width={`${lineWidthOne}%`}
      height="6.4"
    />
    <rect
      x={`calc(100% - ${sideMargin}px - ${lineWidthTwo}%)`}
      y={lineHeight}
      rx="3"
      ry="3"
      width={`${lineWidthTwo}%`}
      height="6.4"
    />
    <rect
      x={`calc(100% - ${sideMargin}px - ${lineWidthTwo}%)`}
      y={lineHeight * 2}
      rx="3"
      ry="3"
      width={`${lineWidthTwo}%`}
      height="6.4"
    />
  </Fragment>
)

const LoaderLTR = () => (
  <Fragment>
    <circle cx={circleSize} cy="23" r={circleSize} />
    <rect
      x={sideMargin}
      y="0"
      rx="4"
      ry="4"
      width={`${lineWidthOne}%`}
      height="6.4"
    />
    <rect
      x={sideMargin}
      y={lineHeight}
      rx="3"
      ry="3"
      width={`${lineWidthTwo}%`}
      height="6.4"
    />
    <rect
      x={sideMargin}
      y={lineHeight * 2}
      rx="3"
      ry="3"
      width={`${lineWidthTwo}%`}
      height="6.4"
    />
  </Fragment>
)

const BlahLoader = ({ isLtr })=>
  <ContentLoader rtl={!isLtr} height="60">
    {isLtr ? <LoaderLTR /> : <LoaderRTL />}
  </ContentLoader>
```

It would be really awesome if the engine could re-calculate for rtl and align items automatically to the right.

**Comment by danilowoz** [comment]
@adamgajzlerowicz I got your point.

I've found a solution to flipped the SVG:
```css
transform: scaleX(-1);
```

Before I implement that, I need to finish the migrate to typescript, then I can test better this solution
But thanks for your feedback

**Comment by adamgajzlerowicz** [comment]
I just simplified my component to use your suggested snipped and it worked perfectly.
Feels to me that adding `rtl` prop should always add that to the component... 
I know you have backwards compatibility to maintain etc.. but well. maybe in next release :)

**Comment by adamgajzlerowicz** [comment]
Well done mate!

I will look at upgrading the package next time I am working on loaders. 
Thanks!
