### ISSUE TITLE
Dynamically update height

### ISSUE THREAD

**Issue by jakeleventhal** [danilowoz/react-content-loader#123]
## What did you do? 
I don't know what the source code is, but the behavior is off.

## What did you expect to happen?
The height to dynamically change with browser size changing.

## What happened actually?
The height doesn't change when the browser shrinks vertically, even though the width changes when the browser shrinks horizontally.

### Which versions of react-content-loader, and which browser are affected by this issue?
3.4.1 - Chrome

**Comment by danilowoz** [comment]
Hey @jakeleventhal 
Could you please send an example in codesandbox or even a code snippet?
I think I have an idea what is happening 

Thanks

**Comment by jakeleventhal** [comment]
https://codesandbox.io/s/84zvwvwv3l

If you shrink the window horizontally, it shrinks - but not if you shrink the window vertically

**Comment by danilowoz** [comment]
Hey @jakeleventhal 
What about this? https://codesandbox.io/s/4xz3xwjm94

Let me know if it works fine

**Comment by jakeleventhal** [comment]
![ezgif-1-afb82b4ae18c](https://user-images.githubusercontent.com/15133828/50351045-ce878f80-04f5-11e9-9072-71c1a7b4ba77.gif)

**Comment by danilowoz** [comment]
Can you take a look again? I think I forgot to save the code 😛

**Comment by jakeleventhal** [comment]
Yes this works! Thanks!
