### ISSUE TITLE
Not able to overlay onto a component

### ISSUE THREAD

**Issue by jakeleventhal** [danilowoz/react-content-loader#124]
## What did you do? 
Not sure what the source code is

## What did you expect to happen?
If there is a component (say a Material-UI card), there is currently no way to overlay the content loader on top of the component so that the content loader is the same size/dimensions as the underlying content.

This results in having a content loader that is not the same size as what replaces it once loading is complete.

### Which versions of react-content-loader, and which browser are affected by this issue?
3.4.1 on Chrome

**Comment by danilowoz** [comment]
Hey @jakeleventhal 
Is it something like this you want to do? #124

**Comment by jakeleventhal** [comment]
Yes

**Comment by jakeleventhal** [comment]
How would this work on something like a Material-UI card though? Or something from a library amcharts since the div is not a fixed size and is an unknown height until it is rendered.
