### ISSUE TITLE
Improv documentation

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/react-content-loader#127]
Needs more information

**Comment by pashadia** [comment]
I'm very interested in further info. Right now, it's not immediately clear how to use it in a custom project.

**Comment by danilowoz** [comment]
Great @pashadia, so here are some points I would like to improve:
- Add a table of content

**Features**
- Add typescript, (in the future version 🎉);

**Usage**
- Installation: ok;
- A full implementation (just copy and paste to work) with a Codepen;
- How to use the [creator](http://danilowoz.com/create-content-loader/);

**Options**
- I'm happy with the table, maybe link some option could help;
- Is there a convention to write it?

**Examples**
- I'm happy with that as well, but if anyone has a suggestion, feel free to improve;

**Similars**
- Ok;

**Development**
- Describe the scripts in the package;
- Describe architecture;

**License**
- Ok;

**Known Issues**
- Add #93 with examples and more details;

------

@jakeleventhal I know what you mean, for the past versions I don't know if there is a way to fix it, but for the future versions, I'm using [semantic-release](https://github.com/danilowoz/react-content-loader/pull/126/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40) which will generate a changelog automatically. If you have any further suggestion, please let me know :)

------

@pashadia I would be really happy if you help with these points, but please let me know which items you'll work on, so we don't work on same things
