### ISSUE TITLE
Full height and width works but causes error

### ISSUE THREAD

**Issue by developdeez** [danilowoz/react-content-loader#129]
Content loader works fine if I enter '100vh' to fill my height but it causes an svg viewbox error.
Can this error be prevented?

**Comment by danilowoz** [comment]
@developdeez maybe this issue can help you #123

**Comment by developdeez** [comment]
Here's an example:
```

export const ProfileLoader = () => (
  <ContentLoader
    height={"100vh"}
    width={"100vw"}
    speed={2}
    primaryColor="#f3f3f3"
    secondaryColor="#ecebeb"
  >
    <rect x="1.05" y="0.00" rx="0" ry="0" width="125.2" height="141.89" />
    <rect x="143.44" y="13.67" rx="0" ry="0" width="139" height="21" />
    <rect x="143.44" y="40.67" rx="0" ry="0" width="108" height="13" />
    <rect x="143.44" y="62.67" rx="0" ry="0" width="56" height="19" />
    <rect x="143.44" y="94.67" rx="0" ry="0" width="84.89" height="32.57" />
    <rect x="208.44" y="62.67" rx="0" ry="0" width="56" height="19" />
    <rect x="273.44" y="62.67" rx="0" ry="0" width="56" height="19" />
    <rect x="243.44" y="94.67" rx="0" ry="0" width="84.89" height="32.57" />
  </ContentLoader>
);
```

**Comment by developdeez** [comment]
@danilowoz that <style> seemed to center it so I guess it's an improvemnt
With set width height and style tag :/
![image](https://user-images.githubusercontent.com/13059525/51797659-8e828f00-21bc-11e9-93ac-688d768e352f.png)



With error + expected sizing :)
![image](https://user-images.githubusercontent.com/13059525/51797654-6abf4900-21bc-11e9-8e5e-86094fab8e8f.png)

**Comment by danilowoz** [comment]
It is happening because I use the width and height in the viewBox attr in SVG, which only accepts numbers. You can use styles when you need to set a custom size:
https://codesandbox.io/s/9ljl1kzj9p

Probably it needs some changes in this pen to reach what you want.

Let me know, if I can help you yet :)

**Comment by danilowoz** [comment]
I hope that worked :)
