### ISSUE TITLE
Default export name is unusable

### ISSUE THREAD

**Issue by gcangussu** [danilowoz/react-content-loader#131]
From `dist/src/Holder.d.ts` lines 4-5:
```ts
declare const _default: (props: IContentLoaderProps) => JSX.Element;
export default _default;
```

When I try to import it I get an error from TSLint:
```
ERROR: (match-default-export-name) /path/to/file.tsx[2, 8]: Expected import 'ContentLoader' to match the default export '_default'.
```

Of course, I could disable this rule or import it as _default, but it would be great - to me and everyone that uses this rule - if we named the `default export` statement properly.

This only affects v4, for previous versions the `@types/react-content-loader` exported it as `ContentLoader`;

I recommend exporting it as `ContentLoader` to keep compatibility with the `@types` package.

**Comment by danilowoz** [comment]
Thanks for your contributions, I think I got the problem.
