### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by virtualLast** [danilowoz/react-content-loader#137]
## What did you do? 
Please include the actual source code causing the issue.
import { Facebook } from 'react-content-loader';
// then in render method
return `<Facebook />`;
## What did you expect to happen?
Please mention the expected behaviour.
See the facebook loader
## What happened actually?
Invariant Violation: Text string must be rendered within a <Text> component, error located at title in Svg
### Which versions of react-content-loader, and which browser are affected by this issue?
Please also mention the version of react.
Everything is the latest

**Comment by rsokz** [comment]
Getting the same issue.

**Comment by danilowoz** [comment]
Hey thanks for sharing it, but  I've made some tests and I didn't get the error.
Could you please send me a codesandbox? Or can you check if it happens in this [pen ](codesandbox.io)? Because for me it works fine. Plus, let me know what exact version (React and package) you are using.

Thanks

**Comment by bfine9618** [comment]
I am recieving this bug as well. I implemented the custom ContentLoader

`
<ContentLoader
				rtl
				height={100}
				width={100}
				speed={2}
				primaryColor="#f3f3f3"
				secondaryColor="#ecebeb"
			>
				<rect x="0" y="70" rx="5" ry="5" width="400" height="400" />
			</ContentLoader>
`

**Comment by IAmWilling** [comment]
Invariant Violation: Invariant Violation: Text strings must be rendered within a <Text> component.

This error is located at:
    in title (created by Svg)
    in svg (created by Svg)
    in Svg (created by Holder)
    in Holder (created by FacebookStyle)
    in FacebookStyle (at itemChild.js:19)
    in RCTView (at View.js:45)
    in View (at itemChild.js:18)
    in ItemChild (at item.js:155)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at TouchableOpacity.js:255)
    in TouchableOpacity (at item.js:147)
    in RCTView (at View.js:45)
    in View (at VirtualizedList.js:1734)
    in CellRenderer (at VirtualizedList.js:687)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:873)
    in RCTScrollView (at ScrollView.js:992)
    in AndroidSwipeRefreshLayout (at RefreshControl.js:169)
    in RefreshControl (at item.js:63)
    in ScrollView (at VirtualizedList.js:1061)
    in VirtualizedList (at FlatList.js:625)
    in FlatList (at item.js:60)
    in PopularItem (at popluar/index.js:49)
    in RCTView (at View.js:45)
    in View (at popluar/index.js:48)
    in StaticContainer (at SceneComponent.js:11)
    in RCTView (at View.js:45)
    in View (at SceneComponent.js:10)
    in SceneComponent (created by ViewPagerAndroid)
    in AndroidViewPager (at ViewPagerAndroid.android.js:265)
    in ViewPagerAndroid (at createAnimatedComponent.js:153)
    in AnimatedComponent (at react-native-scrollable-tab-view/index.js:246)
    in RCTView (at View.js:45)
    in View (at react-native-scrollable-tab-view/index.js:389)
    in ScrollableTabView (at popluar/index.js:39)
    in RCTView (at View.js:45)
    in View (at popluar/index.js:26)
    in Popluar (created by SceneView)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:113)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at createBottomTabNavigator.js:103)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:102)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (at StackViewLayout.js:784)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:783)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:782)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:860)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:311)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at StackViewLayout.js:307)
    in Handler (at StackViewLayout.js:300)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:79)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:215)
    in Transitioner (at StackView.js:22)
    in StackView (created by Navigator)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (at createAppContainer.js:388)
    in NavigationContainer (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)

**Comment by danilowoz** [comment]
Hey, are you guys using this package in React Native? It only works in React web, if so take a look at this [package](https://github.com/virusvn/react-native-svg-animated-linear-gradient). 

Otherwise, if it's happening in React web, please paste a codesandbox, then I can see the problem, because so far I haven't got this error.

Thanks

**Comment by danilowoz** [comment]
BTW, how is it work in RN?
Maybe I can made a fork to support better React Native

**Comment by IAmWilling** [comment]
> 嘿，你们在React Native中使用这个包吗？它只适用于React web，如果是这样，请看一下这个[包](https://github.com/virusvn/react-native-svg-animated-linear-gradient)。
> 
> 否则，如果它发生在React网页上，请粘贴一个代码框，然后我就可以看到问题，因为到目前为止我没有收到此错误。
> 
> 谢谢
Thank you very much, I will try it.

**Comment by bfine9618** [comment]
@danilowoz Thanks - sorry about the confusion.

**Comment by mayconmesquita** [comment]
@danilowoz This would be nice in RN. The closest RN solution sucks. Do you have any plans to support it on native apps? Thank you!

**Comment by danilowoz** [comment]
Yes, now that you mentioned that, I could figure out a way for the package works in React Native.
Every helping is welcoming :)

**Comment by giacomocerquone** [comment]
@danilowoz I still have this problem! Just installed now v4.3.0 and it keeps erroring me an invariant violation

![Screenshot_1569826530](https://user-images.githubusercontent.com/9303791/65855776-1b8b7280-e360-11e9-9f99-1c58674f9592.png)

I'm on expo sdk 34, maybe it's an upstream issue with the react native svg version?

**Comment by danilowoz** [comment]
Hey @giacomocerquone, could you paste your code here?
That helps me to debug and understand what is happening with your loading

Thanks

**Comment by giacomocerquone** [comment]
@danilowoz shoot, I didn't mention it since it was that simple custom loader example found in the readme:

```
const MyLoader = () => (
  <ContentLoader>
    {/* Only SVG shapes */}    
    <rect x="0" y="0" rx="5" ry="5" width="70" height="70" />
    <rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
    <rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
  </ContentLoader>
)
```

But I imported the non native ContentLoader, this explains the error. Sorry :)

**Comment by witalobenicio** [comment]
Any work on this problem?

**Comment by danilowoz** [comment]
Hey, it seems that you're using React Dom version on React Native.

Are you importing the package from the native version? Like [this](https://github.com/danilowoz/react-content-loader/#native):

```diff
+ import ContentLoader, { Rect, Circle } from 'react-content-loader/native'

const MyLoader = () => (
  <ContentLoader>
+    <Circle cx="30" cy="30" r="30" />
+    <Rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
+    <Rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
  </ContentLoader>
)
```

**Comment by mqtik** [comment]
Just tested, this is working.

Go to https://danilowoz.com/create-content-loader/ -> pick React Native.
