### ISSUE TITLE
Content loader takes a long time to start animating on Firefox

### ISSUE THREAD

**Issue by stxxart** [danilowoz/react-content-loader#138]
## What did you do?

Wanting the following component to animate on Firefox:

```
<ContentLoader
  height={475}
  width={600}
  primaryColor="#FFFFFF"
  secondaryColor="#FFFFFF"
  primaryOpacity={0}
  secondaryOpacity={0.25}>
  <rect x="0" y="0" rx="4" ry="4" width="300" height="150" />
  <rect x="0" y="180" rx="4" ry="4" width="500" height="50" />
  <rect x="0" y="240" rx="4" ry="4" width="600" height="50" />
  <rect x="0" y="300" rx="4" ry="4" width="300" height="50" />
  <rect x="0" y="365" rx="4" ry="4" width="50" height="20" />
  <rect x="65" y="365" rx="4" ry="4" width="100" height="20" />
  <rect x="0" y="435" rx="20" ry="20" width="120" height="40" />
  <rect x="150" y="435" rx="20" ry="20" width="120" height="40" />
  <rect x="300" y="435" rx="20" ry="20" width="120" height="40" />
</ContentLoader>
```

## What did you expect to happen?
I'd expect the component to render and animate on Firefox promptly, as it does on Chrome, Safari, and Opera.

## What happened actually?

When the component is meant to render, nothing appears on Firefox. The component renders correctly in Chrome, Safari, and Opera. Some times it doesn't start animating in time before a flag / variable is changed. Once the flag / variable is changed, the actual content is shown but the content loader actually never appeared.

### Which versions of react-content-loader, and which browser are affected by this issue?

- Issue appears in **Firefox** version _63.0.3_.
- I'm using `react-content-loader` version _4.0.1_ and `react` version _16.8.2_.

**Comment by danilowoz** [comment]
Hey @stxxart  thanks for your report.
I took a look in the latest version of Firefox and in the `63.0.3` and it works fine.
Could you generate a `codesandbox` with this issue? 

It is happening maybe because you are using both color white and opacity? Just an idea, I don't know how your applications look like

Thanks
