### ISSUE TITLE
cant get the animation working 

### ISSUE THREAD

**Issue by kiranbabu189** [danilowoz/react-content-loader#15]
animation for the component is not working.

**Comment by danilowoz** [comment]
@kiranbabu189 Might you give me more details about this problem?

**Comment by kiranbabu189** [comment]
in your demo there's a wave like animation for the loader, but i can't get
the same though i'm using the same with parameters.

**Comment by danilowoz** [comment]
<img width="521" alt="screen shot 2017-07-31 at 09 37 17" src="https://user-images.githubusercontent.com/4838076/28778045-fbb6f188-75d3-11e7-81b5-a8d481be5eba.png">
@kiranbabu189 I got it using your code.

Try it, I created a branch with the name `kiranbabu189-custom-element`
Then install the react storybook and run: `npm run storybook`, you can see the element working

**Comment by kiranbabu189** [comment]
im getting a empty storybook .

**Comment by danilowoz** [comment]
It is very strange. See as it is my browser:
<img width="773" alt="screen shot 2017-07-31 at 19 54 43" src="https://user-images.githubusercontent.com/4838076/28801917-3a066a9e-762a-11e7-9792-798dfd70884a.png">

Can you test on another browser or pc?
