### ISSUE TITLE
Type error when use with typescript

### ISSUE THREAD

**Issue by VuongVu** [danilowoz/react-content-loader#150]
I'm installed react-content-loader@4.2.2 and apply this loader for my project: 
https://github.com/danilowoz/create-content-loader/blob/master/src/Gallery/insertYourLoaderHere/HomePage.js

But it always have error: 
`Type assertion using the '<>' syntax is forbidden. Use the 'as' syntax instead.
'ContentLoader' refers to a value, but is being used as a type here.`
<img width="847" alt="Screen Shot 2019-07-26 at 9 38 05 AM" src="https://user-images.githubusercontent.com/17722393/61921966-1f2e0200-af89-11e9-98d3-e33a4bd3990c.png">

I build with Nextjs + Typescript, this is my tsconfig:
<img width="801" alt="Screen Shot 2019-07-26 at 9 35 57 AM" src="https://user-images.githubusercontent.com/17722393/61921865-cf4f3b00-af88-11e9-83b6-a9a1dd4d627b.png">

plz give me a solution for it.

**Comment by danilowoz** [comment]
Hey @VuongVu 
The first thing that I can see is that your file extension is wrong, there is a difference between `.ts` and `.tsx`. Let me know if it solved your issue

**Comment by VuongVu** [comment]
Yep, i’m fixed it, this is my problem.  Thank u so much. 😖
