### ISSUE TITLE
Doesn't work with Expo (React Native)

### ISSUE THREAD

**Issue by jordymeow** [danilowoz/react-content-loader#157]
Not sure exactly why but the error is this one.

> Tried to register two views with the same name RNSVGRect

**Comment by danilowoz** [comment]
Hey, @jordymeow I just created an Expo app and it works fine for me.
Could do you give me more information? Maybe your steps to add the package or the snippet of your loading.

Thanks

**Comment by g9rga** [comment]
I have the same issue. Simple example crashes expo without logs:

import React from &#x27;react&#x27;;
import ContentLoader, { Rect, Circle } from &#x27;react-content-loader/native&#x27;;

const MyLoader = () =&#x3E; (
    &#x3C;ContentLoader&#x3E;
        &#x3C;Circle cx=&#x22;30&#x22; cy=&#x22;30&#x22; r=&#x22;30&#x22; /&#x3E;
        &#x3C;Rect x=&#x22;80&#x22; y=&#x22;17&#x22; rx=&#x22;4&#x22; ry=&#x22;4&#x22; width=&#x22;300&#x22; height=&#x22;13&#x22; /&#x3E;
        &#x3C;Rect x=&#x22;80&#x22; y=&#x22;40&#x22; rx=&#x22;3&#x22; ry=&#x22;3&#x22; width=&#x22;250&#x22; height=&#x22;10&#x22; /&#x3E;
    &#x3C;/ContentLoader&#x3E;
)

export default MyLoader;

**Comment by danilowoz** [comment]
Hey @g9rga, I just created an app using Expo from scratch with your code and works fine.
Repo is here: https://github.com/danilowoz/react-content-loader-expo-test/blob/master/App.js

Could do you check what I am doing differently for you guys? 

Thanks

**Comment by g9rga** [comment]
@danilowoz finnaly, i found the solution! It links to the issue https://github.com/react-native-community/react-native-svg/issues/1127 . The solution to install react-native-svg: 9.9.2.

**Comment by danilowoz** [comment]
Nice @g9rga, @jordymeow could do you check with it solves your problem?

Let me know about it

**Comment by oxyii** [comment]
@danilowoz I'm not sure that I have the same error but looks it is. Pure `react-native` (without expo) crashed with error "Invariant Violation: Text strings must be rendered within a `<Text>` component." in title (created by Svg).

I think, this is it https://github.com/danilowoz/react-content-loader/blob/c032ca7d2b32232dc793b670329fc2a532890735/src/Svg.tsx#L43

**Comment by g9rga** [comment]
@oxyii you should export Svg from  'react-content-loader/native' for react native

**Comment by oxyii** [comment]
@danilowoz  @g9rga Yep, my bad. I need to sleep. Sorry for the false alarm
