### ISSUE TITLE
React-Native : Animation isn't working

### ISSUE THREAD

**Issue by sliesensei** [danilowoz/react-content-loader#160]
Hello,

My loader's animation isn't working, I am doing something wrong ?
Here's my code :
```
import React from 'react';
import ContentLoader, { Rect, Circle, Facebook }  from "react-content-loader/native"
import {
  View
} from 'react-native';

export default class LoaderHome extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <ContentLoader
        height={160}
        width={400}
        speed={2}
        animate={true}
        primaryColor="#f3f3f3"
        secondaryColor="#ecebeb" >
        <Circle cx="30" cy="30" r="30" />
        <Rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
        <Rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
      </ContentLoader>
    )
  }
}
```
And the result :
<img width="397" alt="Capture d’écran 2019-10-17 à 12 35 21" src="https://user-images.githubusercontent.com/35491204/67001712-a4cdd380-f0da-11e9-837a-125371b2c638.png">

**Comment by danilowoz** [comment]
Hey @sliesensei 
Do you mind to explain what happened with your loader? 
If it was a bug or just a mistake

Thanks

**Comment by sliesensei** [comment]
Hey @danilowoz
Sorry it was a mistake, I forget to rerun 'react-native run-android' !
