### ISSUE TITLE
SVG doesn't render when parent container is set as display flex

### ISSUE THREAD

**Issue by brightpixels** [danilowoz/react-content-loader#161]
## What did you do? 
https://codesandbox.io/s/xenodochial-firefly-jsb14?fontsize=14

````
const MyLoader = () => (
  <ContentLoader height="70" width="300">
    <rect x="0" y="0" rx="5" ry="5" width="70" height="70" />
    <rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
    <rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
  </ContentLoader>
);

const App = () => (
  <div style={{ display: "flex" }}>
    <MyLoader />
  </div>
);
````

## What did you expect to happen?
Content loader to display.

## What happened actually?
Content loader doesn't display (although it renders). Problem appears to be no height or width has been set on the SVG, even though it's set on the container (ContentLoader).

### Which versions of react-content-loader, and which browser are affected by this issue?
Latest version, 4.3.2,  on modern chrome browser.

**Comment by pessato** [comment]
Had a similar issue, got around it by wrapping the loader in a div with a fixed height & width..
https://codesandbox.io/s/muddy-sun-elkng

**Comment by danilowoz** [comment]
Hey, it's a really weird behavior from SVG and I don't have an answer to why it happens.
But I could fix it using `flex :1;` on SVG:

```jsx
<div style={{ display: flex; }}>
   <ContentLoader style={{ flex: 1 }} />
</div>
```

Let me know if it solves your problem

**Comment by danilowoz** [comment]
Any thoughts @pessato @brightpixels?
I'm closing this issue for now

Thanks

**Comment by brightpixels** [comment]
I used the suggested workarounds. Not ideal but does the job. Thank you.
