### ISSUE TITLE
How to do 100% width

### ISSUE THREAD

**Issue by stevensacks** [danilowoz/react-content-loader#162]
I had to figure out how to support 100% width on my own. It's not exactly "easy" but it's possible, and it's worth adding to the documentation. Here is my solution. It involves hooks, though I'm sure it could be done without.

I'm using a wrapper around my app so that's what I want to measure from, but this code can easily be modified to use `window.innerWidth`. The `offset` attribute is if the loader is offset from the left, for example if it's the right column in a flex box.

```javascript
import React, {useEffect, useState} from 'react';
import ContentLoader from 'react-content-loader';
import PropTypes from 'prop-types';

const getCalcWidth = offset =>
    (document.querySelector('.app-wrapper').getBoundingClientRect().width ||
        0) - offset;

const SkeletonLoader = ({children, offset, width, ...props}) => {
    const [calcWidth, setCalcWidth] = useState(
        width === '100%' ? 0 : width || 0
    );

    useEffect(() => {
        const onResize = () => {
            setCalcWidth(getCalcWidth(offset));
        };
        if (width === '100%') {
            window.addEventListener('resize', onResize);
            onResize();
        }
        return () => window.removeEventListener('resize', onResize);
    }, [offset, width]);

    return (
        <ContentLoader
            {...props}
            width={calcWidth}
        >
            {children}
        </ContentLoader>
    );
};

SkeletonLoader.propTypes = {
    children: PropTypes.any,
    offset: PropTypes.number,
    width: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
};

SkeletonLoader.defaultProps = {
    offset: 0,
};

export default SkeletonLoader;
```

I hope somebody finds this helpful. You can use the same technique to do 100% height if you want.

**Comment by danilowoz** [comment]
Hey @stevensacks, thanks for your contributions.
Maybe I didn't get what you wanted to reach, so let me try to understand, is it something like this?
https://codesandbox.io/s/wandering-frog-sezxl?fontsize=14

Where the loading is responsive and even it has a max-width, does it make sense for you? Also, [width should be a number instead of a string ("100%")](https://github.com/danilowoz/react-content-loader/blob/master/src/index.ts#L39). If you would like to set a width in the SVG element, you need to use the style prop.

I hope it helps you, thanks.

**Comment by danilowoz** [comment]
Hey @stevensacks, if you have any doubts or thoughts, please let me know.
I'm closing this issue for now

Thanks

**Comment by dextermb** [comment]
@danilowoz How does the code sandbox example above work in the latest versions? It seems like `ContentLoader` has a default preset that changes this behaviour.

**Comment by danilowoz** [comment]
Hey @dextermb I just updated the [CodeSandbox](https://codesandbox.io/s/wandering-frog-sezxl?fontsize=14&file=/src/index.js) and it still working fine. Are you facing some issues? Please let me know

**Comment by dextermb** [comment]
> Hey @dextermb I just updated the [CodeSandbox](https://codesandbox.io/s/wandering-frog-sezxl?fontsize=14&file=/src/index.js) and it still working fine. Are you facing some issues? Please let me know

Hi. I'm having issues creating a responsive SVG with a `rect` inside of it. Whereas the code sandbox shows a responsive SVG with a prefix. 

Any ideas?

**Comment by danilowoz** [comment]
Would you mind pasting here the snippet you have? Or maybe creating a codesandbox by yourself, and then we'll able to be on the same page.

**Comment by danilowoz** [comment]
@dextermb please check the CodeSandbox link again, I think I got what you were saying and it's right. The key property now to make a component responsible is using the `viewBox` one. Check [this](https://codesandbox.io/s/wandering-frog-sezxl?fontsize=14&file=/src/index.js:668-853) out
