### ISSUE TITLE
needs >= 2 number of colors

### ISSUE THREAD

**Issue by harshvitra** [danilowoz/react-content-loader#164]
## What did you do? 
import ContentLoader, { Rect, Circle }  from "react-content-loader/native"

const MyLoader = () => (
  <ContentLoader
    height={150}
    width={300}
    speed={2}
    primaryColor="#f3f3f3"
    secondaryColor="#ecebeb"
  >
    <Circle cx="88" cy="75" r="60" />
    <Circle cx="180" cy="45" r="0" />
  </ContentLoader>
)

## What did you expect to happen?
Expected a loader

## What happened actually?
Got error which read - needs >= 2 number of colors

Latest version of React and 0.59 React Native, Running on Android

**Comment by harshvitra** [comment]
@danilowoz do you have any idea on this.

**Comment by danilowoz** [comment]
Hey @harshvitra really sorry about the delay, I have been quite busy last weeks.

I just init a project from scratch using the following code and it works fine:

```
import ContentLoader, {Rect, Circle} from 'react-content-loader/native';

const MyLoader = () => (
  <ContentLoader
    height={150}
    width={300}
    speed={2}
    primaryColor="#f3f3f3"
    secondaryColor="#ecebeb">
    <Circle cx="88" cy="75" r="60" />
    <Circle cx="180" cy="45" r="0" />
  </ContentLoader>
);
```

I don't know if you notice it, but your snippet above was not completely right, please try mine one.

If it doesn't work anyway, please create a repo or send me your complete code with the versions running there.

Thanks

**Comment by danilowoz** [comment]
I hope everything is clear, let me know if you need any extra help
