### ISSUE TITLE
image jump using placeholder

### ISSUE THREAD

**Issue by Mohammedalasaad** [danilowoz/react-content-loader#166]
Hi,
Is there anyway to show the image smooth without jump while using content-loader.

Regards

**Comment by danilowoz** [comment]
Hey, what you mean jump? 
Have you tried to disable the animate?
Take a look at here https://github.com/danilowoz/react-content-loader#animate-boolean

Thanks

**Comment by Mohammedalasaad** [comment]
Hi,
I mean u know image need sometime until its fully loaded.. And I want to keep show the contnt-loader until the image fully loaded. I get the image from json api endpoint.

example on the right side here:
https://arunmichaeldsouza.com/img/blogs/loading-images-gracefully-with-react-image-appear/2.gif

**Comment by danilowoz** [comment]
Hey, I'm not sure if I got your point, but I guess you would like to show the `ContentLoader` while the image is loading right? Then, when image is completely loaded, hide the `ContentLoader` and show the image, is that it? 

If so, you could add an event listener `onLoad` on the image. Then it lets you know the right moment when image is loaded.

Let me know your thoughts about it

**Comment by Mohammedalasaad** [comment]
Hi Danilowoz,
Yes exactly I tried to make that with onload , but not sure really how to make it.  Thats what I have now : 
` { 
                                    this.state.partner ?
                                        this.state.partner.headerImageUrl ?
                                            <img className="hero-banner" src={this.state.partner.headerImageUrl} />
                                    :  ''
                                     : <ContentLoader height={115} speed={6} primaryOpacity="0.25" primaryColor="#5d5d5d" secondaryColor="#5d5d5d" secondaryOpacity="0.50">
                                        <rect x="0" y="0" rx="0" ry="0" width="100%" /> 
                                    </ContentLoader>                                     
                                    }   `

**Comment by danilowoz** [comment]
I just made a sample code, take a look at this https://codesandbox.io/s/priceless-zhukovsky-z4u5q

I hope it solves your issue

**Comment by Mohammedalasaad** [comment]
Thank you so much Danilowoz for the example :)
