### ISSUE TITLE
ViewBox prop does not exist on type

### ISSUE THREAD

**Issue by cloudratha** [danilowoz/react-content-loader#170]
## What did you do? 
```jsx
<ContentLoader viewBox="" />
```

## What did you expect to happen?
As mentioned in the docs it should accept the viewBox prop.

## What happened actually?
Typescript error:
```
Type '{ viewBox: string; }' is not assignable to type 'IntrinsicAttributes & IContentLoaderProps'.
  Property 'viewBox' does not exist on type 'IntrinsicAttributes & IContentLoaderProps'.
```

### Which versions of react-content-loader, and which browser are affected by this issue?

react-content-loader: ^4.3.3
react:^16.11.0

**Comment by cloudratha** [comment]
Perhaps if `IContentLoaderProps` extends `SVGAttributes<SVGElement>` might do the trick?

**Comment by danilowoz** [comment]
Thanks for letting me know it.
You were right, it could extend from `SVGAttributes<SVGElement>` and I was able removing some unnecessary keys on types.
