### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alex-mironov** [danilowoz/react-content-loader#178]
The components created with `react-content-loader` seem to be leaking memory. 

```
import React from 'react'
import ContentLoader, { Rect } from 'react-content-loader/native'

const LoaderSkeleton = () => (
  <View style={{ flex: 1 }}>
    <ContentLoader height={96}>
      <Rect width={64} height={64} />
      <Rect x={64 + 12} y={0} width={80} height={18} />
      <Rect x={64 + 12} y={18 + 4} width={230} height={22} />
      <Rect x={64 + 12} y={18 + 4 + 22} width={112} height={22} />
      <Rect x={64 + 12} y={18 + 4 + 22 + 22 + 12} width={160} height={18} />
    </ContentLoader>
  </View>
)

export default LoaderSkeleton
```

<img width="1278" alt="Screen Shot 2020-01-24 at 16 33 19" src="https://user-images.githubusercontent.com/2544767/73076858-a6701a00-3ec7-11ea-95b6-f139e3428596.png">

Libraries:
```
    "react-content-loader": "^4.3.4",
    "react-native-svg": "^11.0.1",
```
Is it a known issue?

**Comment by danilowoz** [comment]
Hey, thanks for letting me know about this issue.
How can I check this information as you did? What tool is this?

**Comment by alex-mironov** [comment]
<img width="563" alt="Screen Shot 2020-01-24 at 18 42 03" src="https://user-images.githubusercontent.com/2544767/73086393-3ec2ca80-3ed9-11ea-869d-dbab2bb7a437.png">

@danilowoz it's xCode profiler. You can run the app, and then go `Product/Profile`. In the profile window you can choose `Leaks`

<img width="774" alt="Screen Shot 2020-01-24 at 18 47 08" src="https://user-images.githubusercontent.com/2544767/73086831-0a9bd980-3eda-11ea-8635-45f085633e17.png">

Then just press Record in the left top corner.

**Comment by javiercr** [comment]
We're also experiencing memory leaks on React Native and really high CPU usage (when `animate` is set to true).
