### ISSUE TITLE
preserveAspectRatio="none" doesn't stretch SVG in v5.x, works in v4.x

### ISSUE THREAD

**Issue by hinok** [danilowoz/react-content-loader#184]
## What did you do? 

**v5.0.2 (doesn't work):** https://codesandbox.io/s/optimistic-cdn-hnz4q
**v4.3.4 (works):** https://codesandbox.io/s/winter-cdn-90j14

```js
import React, { Component } from "react";
import ContentLoader from "react-content-loader";

class SkeletonText extends Component {
  shouldComponentUpdate() {
    return false;
  }

  style = {
    width: "100%",
    height: "235px"
  };

  render() {
    return (
      <ContentLoader
        height={235}
        width={320}
        speed={2}
        backgroundColor="#f3f3f3"
        foregroundColor="#ecebeb"
        preserveAspectRatio="none"
        style={this.style}
        uniqueKey="5bfe76a3092a2"
      >
        <rect x="0" y="0" rx="2" ry="2" width="280" height="10" />
        <rect x="0" y="25" rx="2" ry="2" width="320" height="10" />
        <rect x="0" y="50" rx="2" ry="2" width="280" height="10" />
        <rect x="0" y="75" rx="2" ry="2" width="200" height="10" />
        <rect x="0" y="100" rx="2" ry="2" width="310" height="10" />
        <rect x="0" y="125" rx="2" ry="2" width="320" height="10" />
        <rect x="0" y="150" rx="2" ry="2" width="150" height="10" />
        <rect x="0" y="175" rx="2" ry="2" width="220" height="10" />
        <rect x="0" y="200" rx="2" ry="2" width="210" height="10" />
        <rect x="0" y="225" rx="2" ry="2" width="180" height="10" />
      </ContentLoader>
    );
  }
}

export default SkeletonText;
```

## What did you expect to happen?
SVG should be stretched

## What happened actually?
SVG is not stretched in `5.0.2`, it's stretched in `4.3.4`.

### Which versions of react-content-loader, and which browser are affected by this issue?

Affected `v5.x`, works on `v4.x`, all browsers.

### Why?

In `v5.0.2` the property `viewBox` is not added to SVG which break stretching.

![video](https://user-images.githubusercontent.com/1313605/75036442-2337e900-54b2-11ea-86f4-37323f52e45e.gif)

**Comment by danilowoz** [comment]
Hey @hinok, sorry for this unexpected behavior.
As part of the breaking change of the last major release, it is necessary to pass the attribute `viewBox`, that was generated automatically on v4. Maybe [creator](http://danilowoz.com/create-content-loader/) would be useful for you, to avoid future API mistakes.

So, as `ContentLoader` returns a regular SVG, so the proposal of the v5 is to stop handling/creating unexpected attributes. As it's just an SVG, so use it as an SVG.

Hope it helps you
