### ISSUE TITLE
SSR Warning, Prop id not match

### ISSUE THREAD

**Issue by rifky-vs** [danilowoz/react-content-loader#185]
I'm using NextJs and react-content-loader shows me this error

```Prop `id` did not match. Server: "ry4czal-aria" Client: "42c1jml-aria```

**Comment by danilowoz** [comment]
Hey, I think you're looking for the prop `uniqueKey`, [see](https://github.com/danilowoz/react-content-loader#uniquekey-string---web-only).

Let me know if it works for you.
