### ISSUE TITLE
Run local build w/ RN

### ISSUE THREAD

**Issue by ds8k** [danilowoz/react-content-loader#187]
I'm trying to work on a fork of this library but unfortunately I can't seem to get it to build in way that my RN project likes it. My steps:

```
cd react-content-loader
npm i
npm run build
cd ../rn-app
npm link ../react-content-loader
```

It seems like the version that gets pulled from `npm` is structured in a totally different way than what gets built. I'm seeing folders named "stylized" that I don't get when doing `npm run build`

**Comment by ds8k** [comment]
When I tried doing that I wasn't able to run my RN project. The bundler complained about `react-native-svg` and trying to find it in `rn-app/react-content-loader/node_modes/react-native-svg`. Do I need to add anything special to my metro config?

**Comment by danilowoz** [comment]
Hey, `react-native-svg` is a [dependency](https://github.com/danilowoz/react-content-loader#for-react-native) of Native version.

**Comment by ds8k** [comment]
@danilowoz Yes I'm aware of that and have it installed and linked since I'm currently using `react-content-loader` in my app. I'm trying to fix performance issues by removing the `setState` that's in the Native `Svg.tsx` file, but I need to test my changes locally before making a PR.

**Comment by danilowoz** [comment]
Hey @ds8k, do you have any progress with the performance improvement? 
I've seen some applications with memory leak, and I would like to solve it

Thanks, let me know your thoughts

**Comment by ds8k** [comment]
@danilowoz Sure, I can just post here what I was thinking about doing.

Right now the code creates an animated value and adds a listener to it. The listener updates a state value as the value is animated. This isn't performant, as you lose out on the state benefits Animated values have.

I was planning on creating an animated `Stop` component like this:

```
const AnimatedStop = Animated.createAnimatedComponent(Stop)

offset: new Animated.Value(0)
 
<AnimatedStop offset={this.offset} stopColor={backgroundColor} />
```

You can interpolate the same animated value for the other two AnimatedStops.

**Comment by danilowoz** [comment]
Hey @ds8k, thanks for your helping.
I just opened a PR using this approach, it would be nice to have your review there.

**Comment by plrdev** [comment]
@danilowoz Hi, I also forked the project as I have an idea for a small PR, but I am struggling to get it working as a local build for React Native. Could you please be a bit more specific of your development setup for RN? This could be worthy of adding to the README as well.

As you mentioned, bundler not working with symlinks makes it non-trivial. I tried forking and building the local build, then adding it as a file dependency `"react-content-loader": "file://../react-content-loader/"` but I get an error:

 ```Error: Unable to resolve module `react-content-loader/native` from `App.js`: react-content-loader/native could not be found within the project or in these directories:
  node_modules/react-content-loader```

**Comment by danilowoz** [comment]
Hey @plrdev thanks for letting me know that this is still an issue. 

So there is an easy way to manage this issue:
- Create a new React Native project from scratch;
- Clone the fork into the project you just created;
- Import from the work, like: `import ContentLoader from "./react-content-loader`

It's really important that the fork is into the same folder of React Native, otherwise it will not work.

Anyway, thanks to rise this issue again, I'll figure out a way to improve this flow.
