### ISSUE TITLE
Why the default skeleton change?

### ISSUE THREAD

**Issue by tknickman** [danilowoz/react-content-loader#194]
## What did you do? 

We have several components in our code base utilizing the skeleton loader as:
`<ContentLoader height={x} width={y} {...props} />`
to render a simple box skeleton

## What did you expect to happen?
This should render a box with the passed in height and width

## What happened actually?
It renders the Facebook post skeleton

### Which versions of react-content-loader, and which browser are affected by this issue?
`react-content-loader > 5`

## Summary
We recently updated react-content-loader to > 5 in our codebase and just noticed several skeletons breaking because we were relying on the the default `Box` being used when no children are passed in.

We can certainly update our code to work around this or pin react-content-loader back for now to fix this, But I'm just curious what the reasoning was to change the default from Box to the facebook post skeleton? 

Box seems like a _much_ more universal and reasonable default. 

Happy to discuss more but regardless, thanks for the great component!

**Comment by tknickman** [comment]
For anyone facing a similar issue. We fixed this by wrapping the ContentLoader component and restoring the default component functionality:

```
import React from 'react';
import PropTypes from 'prop-types';
import ContentLoader as CL from 'react-content-loader';

const InitialComponent = ({ width, height }) => (
  <rect x="0" y="0" rx="5" ry="5" width={width} height={height} />
);

InitialComponent.propTypes = {
  height: PropTypes.number,
  width: PropTypes.number,
};

InitialComponent.defaultProps = {
  height: 130,
  width: 400,
};

const ContentLoader = props => {
  const { children, ...contentLoaderProps } = props;

  return (
    <CL {...contentLoaderProps}>
      {children || <InitialComponent {...props} />}
    </CL>
  );
};

export default ContentLoader
```

**Comment by fnhipster** [comment]
You could also wrap it as

```
import React from 'react'
import { Component } from '../../lib'
import ContentLoader from 'react-content-loader'

export type SkeletonProps = {
    width: number
    height: number
}

export const Skeleton: Component<SkeletonProps> = ({ children, width, height, ...props }) => {
    return (
        <ContentLoader
            viewBox={`0 0 ${width} ${height}`}
            {...props}
        >
            {children}
        </ContentLoader>
    )
}

```

**Comment by danilowoz** [comment]
Hey @tknickman, that's is the [main break change from v5](https://github.com/danilowoz/react-content-loader/releases/tag/v5.0.0). 

Love your solutions @fnhipster, or you even could have done something like this:
```jsx
<ContentLoader width={width} height={height} viewBox={`0 0 ${width} ${height}`} />
```

**Comment by tknickman** [comment]
Yea for sure I noticed it in the breaking changelog - that makes sense. I just wasn't clear on the reasoning behind using the facebook post for the default as it's a lot less generic of a default than a box. 

But regardless we're all set now 👍

Thanks again!
