### ISSUE TITLE
NPM installing Error

### ISSUE THREAD

**Issue by vish2595** [danilowoz/react-content-loader#195]
## What did you do? 
While npm install getting this.
![Screenshot 2020-04-17 at 3 50 56 PM](https://user-images.githubusercontent.com/21971126/79559384-3be40a00-80c3-11ea-9ef7-d73f820eaf4a.png)
![Screenshot 2020-04-17 at 3 52 52 PM](https://user-images.githubusercontent.com/21971126/79559511-81083c00-80c3-11ea-8746-44928ffe588b.png)

**Comment by danilowoz** [comment]
It seems an npm bug, maybe a bad request or service unavailable. 
Have you tried to install the latest version (5.0.4)?

**Comment by vish2595** [comment]
@danilowoz Yes I tried latest version many time and getting same.

**Comment by vish2595** [comment]
![Screenshot 2020-04-17 at 4 17 27 PM](https://user-images.githubusercontent.com/21971126/79561400-f0335f80-80c6-11ea-9902-842e37282ae7.png)
This is showing on NPM page of lib.

**Comment by vish2595** [comment]
@danilowoz Have you checked issue?

**Comment by danilowoz** [comment]
Here's working fine, even with old versions. Don't you have any kind of restriction on your network?
As Npm ([npm status](https://status.npmjs.org/)) there is no accident recently, I don't have any clue here.

<img width="726" alt="Screenshot 2020-04-17 at 12 06 14" src="https://user-images.githubusercontent.com/4838076/79563003-dc2a3680-80a3-11ea-95ed-afa3baa6874f.png">

**Comment by danilowoz** [comment]
Hope it has been solved.
