### ISSUE TITLE
Fluid size

### ISSUE THREAD

**Issue by wahxf** [danilowoz/react-content-loader#196]
如何适配在移动端的宽高呢，不同的手机差别还是很大

**Comment by danilowoz** [comment]
Hey, first of all from now, let's speak in the main language of programming and use English, alright? 

So which environment are you, web or native? 
You could achieve fluid size behaviour like a regular SVG, I guess in Native it works the same:

```
<ContentLoader width="100" height="100" viewBox="0 0 100 100" style={{ width: "100%", height: "auto" }} /> 
```

Let me know if it helps you
