### ISSUE TITLE
Warning: Prop `id` did not match. Server: "ybmwonl-aria" Client: "lcbu8e-aria"

### ISSUE THREAD

**Issue by mehbubrashid** [danilowoz/react-content-loader#198]
i am using next.js.On browser console, its showing the following warning.

```
Warning: Prop `id` did not match. Server: "ybmwonl-aria" Client: "lcbu8e-aria"
    in title (created by SVG)
    in svg (created by SVG)
    in SVG (created by ContentLoader)
    in ContentLoader (created by CatalogMagic)
```

**Comment by danilowoz** [comment]
Hey @mehbubrashid, please take a look at this section:
https://github.com/danilowoz/react-content-loader#server-side-rendering-ssr---match-snapshot

Let me know if it solves your problem

**Comment by mehbubrashid** [comment]
Thanks! this fixed my issue

**Comment by mehbubrashid** [comment]
Hi,but after setting `<CatalogMagic uniqueKey="my-random-valye" style={{ width: '100%' }}></CatalogMagic>` the animation does not load at all!

**Comment by danilowoz** [comment]
Hey, could you send a sample code to run locally?
Because I've run some tests here and everything works fine.

THanks

**Comment by iamrashed01** [comment]
for me  this problem is solved by passing "uniqueKey" 
```
{isLoading && (
  <ContentLoader uniqueKey="products" className="m-3" viewBox="0 0 100 30">
    <rect x="0" y="0" rx="1" ry="1" width="24" height="30" />
    <rect x="25" y="0" rx="1" ry="1" width="24" height="30" />
    <rect x="50" y="0" rx="1" ry="1" width="24" height="30" />
    <rect x="75" y="0" rx="1" ry="1" width="24" height="30" />
  </ContentLoader>
)}
```

**Comment by Sergioamjr** [comment]
I solved this using the `uniqueKey` property, however, I was using a title and my loader had the color black. I figured out it should not have spaces, I solved formatting the title with 

```js
uniqueKey={title.split(' ').join().toLowerCase().replace(/,/g, '')}
```

**Comment by rafzan** [comment]
Hey, this is happening to me after I updated to Next13. I'm using the `/app` directory.
Setting a `uniqueKey` isn't working.

**Comment by MwSpaceLLC** [comment]
for nextjs, work 100%

```js
import ContentLoader from "react-content-loader";
import {useId} from "react";

export default function SingleLineLoader({className, width = 250, height = 10}) {

    const uniqueKey = useId();

    return (
        <ContentLoader
            speed={3}
            uniqueKey={uniqueKey}
            className={className}
            height={height} viewBox={`0 0 ${width} ${height}`}
            backgroundColor="#f3f3f3"
            foregroundColor="#ecebeb"
        >
            <rect width={width} height={height}/>
        </ContentLoader>
    )
}
```
