### ISSUE TITLE
Question: Is there any way to make a soft transition to the real content?

### ISSUE THREAD

**Issue by victorpinheiro** [danilowoz/react-content-loader#199]
Hi guys,
I'd like to have a fade-out animation when the skeleton is replaced by the real content instead of it justing being replaced, so the user can have a smoother experience. How would be the best way to do it?

**Comment by danilowoz** [comment]
Hey @victorpinheiro 

There is no official approach for that, it will depend on your styling lib, the content and HTML structure, but here's possible way to achieve it: https://codesandbox.io/s/friendly-hugle-517e7?file=/src/App.js

Let me know if it helps you.

**Comment by victorpinheiro** [comment]
Works like a charm!
Thanks @danilowoz

**Comment by dkolarev** [comment]
> Hey @victorpinheiro
> 
> There is no official approach for that, it will depend on your styling lib, the content and HTML structure, but here's possible way to achieve it: https://codesandbox.io/s/friendly-hugle-517e7?file=/src/App.js
> 
> Let me know if it helps you.

I'm trying to do the same thing, but your link doesn't work anymore. Can you send the example again?

**Comment by danilowoz** [comment]
Hey, here's an example using framer-motion:
https://codesandbox.io/s/framer-motion-transition-2roey?file=/src/App.js
