### ISSUE TITLE
New component list with bullets in SVG

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/react-content-loader#20]
I think the project needs a new component like a traditional list with bullets, there is a list component, maybe just need to improve that.

**Comment by pszczolas** [comment]
I wuold like to try. Should result be something like that? (fast sketch):
![scretch](https://user-images.githubusercontent.com/14974507/31946710-d1bc4170-b8d2-11e7-8989-99dce1f3b0da.PNG)

**Comment by danilowoz** [comment]
@pszczolas, I think will be cool like this:

• ————
• ————
• ————

You know?

**Comment by danilowoz** [comment]
Thanks @rakeshgunduka
