### ISSUE TITLE
centering the content

### ISSUE THREAD

**Issue by Ladvace** [danilowoz/react-content-loader#207]
Is there any way to center the elements inside `ContentLoader` horizontally (or vertically) based on the size of the page?

**Comment by danilowoz** [comment]
Hey @Ladvace, thanks for posting your question here.

So answering your question, yes there's a way. I just made a CodeSandBox which shows it:
https://codesandbox.io/s/center-loading-mh42f

Let me know if it solves your issue.

**Comment by danilowoz** [comment]
I'll assume that it has been solved.
