### ISSUE TITLE
ariaLabel attribute not working

### ISSUE THREAD

**Issue by Ladvace** [danilowoz/react-content-loader#208]
I was trying to remove the **ariaLabel** but setting `ariaLabel ` to false does not work. I gave a look to the old commits and seems you've removed it in the V5. If yes why?

**Comment by danilowoz** [comment]
Instead of `ariaLabel` use `title`, which fits better for a18n propose.

Let me know if it solves your issue.

**Comment by Ladvace** [comment]
yes it works, Thanks
