### ISSUE TITLE
I want to contribute to react-content-loader design tool

### ISSUE THREAD

**Issue by doong-jo** [danilowoz/react-content-loader#213]
Hello danilowoz !

I am using this library with my design tools for my project. I want to add some functionality to the design tool, can I contribute it?

https://danilowoz.com/create-content-loader/

**Comment by danilowoz** [comment]
Hey @doong-jo 
Sure, feel free to add it. Just let me know if you need any help to understand the codebase - I know that is not so legible - or with design improvements. 

Thanks
