### ISSUE TITLE
Content loader is not visible on ios

### ISSUE THREAD

**Issue by siwa1208** [danilowoz/react-content-loader#216]
## What did you do? 
Please include the actual source code causing the issue.
`import React from "react"
import ContentLoader from "react-content-loader/native"
import {Rect} from 'react-native-svg'
import Colors from '../../styles/Colors'

const ListLoader = props => (
  <ContentLoader
  height={110}
  width="100%"
  style={{width:"100%"}}
  speed={1}
  backgroundColor="orange"
  foregroundColor="purple"
  {...props}
>
  <Rect x="0" y="8" rx="3" ry="3" width="90" height="90" />
	<Rect x="100" y="10" rx="3" ry="3" width="190" height="8" />
	<Rect x="290" y="30" rx="3" ry="3" width="95" height="8" />
	<Rect x="100" y="50" rx="3" ry="3" width="95" height="7" />
	<Rect x="100" y="70" rx="3" ry="3" width="65" height="7" />
  <Rect x="100" y="90" rx="3" ry="3" width="120" height="6" />
</ContentLoader>
)

export default ListLoader;`

## What did you expect to happen?
Please mention the expected behaviour.

## What happened actually?
It works on Android but it doesn't works on IOS the loader is not visible
### Which versions of react-content-loader, and which browser are affected by this issue?
Please also mention the version of react.
 "react-content-loader": "^5.1.0"
react-native-cli: 2.0.1
react-native: 0.61.4
"expo": "^36.0.0"

**Comment by danilowoz** [comment]
Hey @siwa1208, sorry for the late answer.
In my internal test it works fine, could you please provide more information about your issue?
Looking for your snippets, doesn't it missing the children? Maybe that's your issue.

## My tests
```jsx
import React from "react";
import { View } from "react-native";

import { Facebook } from "react-content-loader/native";

const MyFacebookLoader = () => (
  <Facebook
    height={110}
    width="100%"
    style={{ width: "100%" }}
    speed={1}
    backgroundColor="orange"
    foregroundColor="purple"
  />
);

export default function App() {
  return (
    <View style={{ paddingTop: 100 }}>
      <MyFacebookLoader />
    </View>
  );
}
```

<img width="564" alt="Screenshot 2020-08-17 at 20 30 55" src="https://user-images.githubusercontent.com/4838076/90436430-92407400-e0c8-11ea-9674-81663e2a9e37.png">

**Comment by siwa1208** [comment]
Hello so I've done something like that 

this one is my loader file : 

```
import React from "react"
import ContentLoader, { Rect} from "react-content-loader/native"

const CardLoader = props => (

  <ContentLoader
  height={110}
  width="100%"
  speed={1}
  backgroundColor="#f3f3f3"
  foregroundColor="#c2c2c2"
  ariaLabel={'Chargement en cours...'}
  {...props}
>
  <Rect x="0" y="8" rx="3" ry="3" width="90" height="90" />
	<Rect x="100" y="10" rx="3" ry="3" width="190" height="8" />
	<Rect x="290" y="30" rx="3" ry="3" width="95" height="8" />
	<Rect x="100" y="50" rx="3" ry="3" width="95" height="7" />
	<Rect x="100" y="70" rx="3" ry="3" width="65" height="7" />
  <Rect x="100" y="90" rx="3" ry="3" width="120" height="6" />
</ContentLoader>
) 
export default CardLoader;
```

This is one of my components where I call the loader : 
 ```
_getList = () => {
        return (
            <FlatList
                ...
                ListFooterComponent={() => {
                    let rows = [];
                    for(let i=0; i < this.nbPlaceholder; i++) {
                        rows.push(<CardLoader key={i}/>)
                    }
                    return (
                        this.state.loading && !this.state.getMoreFinish &&
                        <View>
                            {rows}
                        </View>
                    );
                }}
            />
        )
    }
```
On Android phone it is working well but on IOS none of the loader is showing..
Thanks for your help

**Comment by danilowoz** [comment]
Hey @KieranHa, thanks for left more information, but I still have no clue here.
Do you have any extra information? Some snippets, screenshot, device information

react-native-svg@12.1.0

```jsx
import ContentLoader, { Rect } from "react-content-loader/native";

const CardLoader = (props) => (
  <ContentLoader
    height={110}
    width="100%"
    speed={1}
    backgroundColor="#f3f3f3"
    foregroundColor="#c2c2c2"
    ariaLabel={"Chargement en cours..."}
    {...props}
  >
    <Rect x="0" y="8" rx="3" ry="3" width="90" height="90" />
    <Rect x="100" y="10" rx="3" ry="3" width="190" height="8" />
    <Rect x="290" y="30" rx="3" ry="3" width="95" height="8" />
    <Rect x="100" y="50" rx="3" ry="3" width="95" height="7" />
    <Rect x="100" y="70" rx="3" ry="3" width="65" height="7" />
    <Rect x="100" y="90" rx="3" ry="3" width="120" height="6" />
  </ContentLoader>
);

export default function App() {
  return (
    <View style={{ paddingTop: 100 }}>
      <FlatList
        ListFooterComponent={() => {
          let rows = [];
          for (let i = 0; i < 10; i++) {
            rows.push(<CardLoader key={i} />);
          }
          return <View>{rows}</View>;
        }}
      />
    </View>
  );
}
```

<img width="564" alt="Screenshot 2020-08-24 at 22 39 41" src="https://user-images.githubusercontent.com/4838076/91099160-bcf77300-e65a-11ea-8531-18d8e44ce982.png">
