### ISSUE TITLE
Improve React Native development documentation

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/react-content-loader#219]
As discussed in https://github.com/danilowoz/react-content-loader/issues/187 it still has room to improve how the React Native project is initialized. Maybe create a folder with examples, where it can use the main codebase to make some changes.

**Comment by HunainHumail** [comment]
Hey! I would like to work on this issue!

**Comment by danilowoz** [comment]
Hey @HunainHumail go on, it's yours :)

**Comment by bntzio** [comment]
@danilowoz you mean creating an `examples` folder with a boilerplate for a react native project using `react-content-loader`? What are your thoughts on implementing a yarn workspace to link the lib to the examples for easier lib development?

**Comment by danilowoz** [comment]
I'd say create proper documentation to this process:
> My development process is to clone the package on a React Native already working and get the
package locally, like import ContentLoader from "./react-content-loader.

As far as I know, yarn workspace will not work in this case. As metro, which is the React Native compiler, doesn't support symbolic links, it will not able to reach the main package. 

Do you have anything else in mind?

Thanks for your contribution
