### ISSUE TITLE
React Native Problems with initial X1/X2 positions for the linear gradient

### ISSUE THREAD

**Issue by listatt** [danilowoz/react-content-loader#221]
## What did you do? 
First of all, thank you for this amazing library. I use ContentLoader for implementing a skeleton placeholder loader.

## What did you expect to happen?
The initial position for the linear gradient is beyond the left border

![image](https://user-images.githubusercontent.com/10587186/96348076-c4615880-10ae-11eb-93d2-0022dc67640c.png)

## What happened actually?
The initial position for the linear gradient isn't beyond the left border, it is located in the middle. Since the animation has a delay, it looks stuck on the beginning. 
The values `x1, x2` are interpolated on the input range `[-1,2]`, the first `animatedValue` value is not `-1`, but set to `0` (https://github.com/danilowoz/react-content-loader/blob/master/src/native/Svg.tsx#L26), if the initial position set to `-1` it works as expected.

![image](https://user-images.githubusercontent.com/10587186/96348067-b7dd0000-10ae-11eb-8b08-c782967e204f.png)

### Which versions of react-content-loader, and which browser are affected by this issue?

"Platform": "iOS / Android",
"react": "16.11.0",
"react-content-loader": "^5.1.1",

**Comment by danilowoz** [comment]
Nice catch @listatt, I'm going to fix it. 
Thanks for letting me know
