### ISSUE TITLE
Strange memory consumption

### ISSUE THREAD

**Issue by masakotoda** [danilowoz/react-content-loader#223]
## What did you do? 
1. Open https://codesandbox.io/s/moojk887z9 in Microsoft Edge 86.0.622.48 (Official build) (64-bit)
2. Add 25 more instances of "MyLoader"
3. Open Visual Studio and attach the renderer process for https://moojk887z9.csb.app/ (one of "msedge.exe --type=renderer")
4. Minimize Microsoft Edge window
5. Leave it overnight
6. Restore Microsoft Edge window
7. Observe strange memory consumption in Visual Studio debugger
![image](https://user-images.githubusercontent.com/1369760/96903008-16f19a80-144a-11eb-9480-79e7719e2577.png)

## What did you expect to happen?
Memory consumption to be flat.

## What happened actually?
Memory consumption spike observed.

### Which versions of react-content-loader, and which browser are affected by this issue?
https://codesandbox.io/s/moojk887z9 seems to use 4.0.0. It might have been fixed already.

**Comment by masakotoda** [comment]
It might be simply a bug from chromium. Reported https://bugs.chromium.org/p/chromium/issues/detail?id=1141881

**Comment by danilowoz** [comment]
Hey, thanks for reporting this.
I've been struggling with this issue a long time, and so far I haven't found any final solution.

Anyway, let's keep the focus in #125

**Comment by masakotoda** [comment]
This is probably different issue from #125. Because this wasn't happening with chromium 75 which was released in 2019. And it's definitely happening with chromium 83+. #125 is reported in 2018.
