### ISSUE TITLE
Making react-content-loader responsive

### ISSUE THREAD

**Issue by TNBoiBoi** [danilowoz/react-content-loader#228]
## What did you do? 
Hello, I'm trying to make it responsive to screen size.
But I can't seem to make it work, I searched online and saw your documentation but it is very minimal and doesn't explain how to actually do it, I added this Code component but it didn't really do anything , Because I believe I don't know how to use it.
If you can help me figure out how to actually make it responsive I'd appreciate it, and I'll open a thread in stackexchange in order to provide people who also didn't manage to figure it out make it responsive.
BTW it's for react native.

## What did you expect to happen?
Change the content based on screen size,

## What happened actually?
This is the code I have in my content loader
I don't understand how can I turn this SVG paths to a reponsive size because it is all so fixed in size for example width="140" or the actual axis of where it should be positioned.
And I can't seem to find anything about it online.
import React from 'react';
import ContentLoader, {
Rect,
Circle,
Code,
Path,
Facebook,
} from 'react-content-loader/native';
const CommunityLoadingIndicator = () => (
<ContentLoader
speed={0.35}
animate
width={414}
height={896}
viewBox="0 0 414 896"
backgroundColor="#f3f3f3"
foregroundColor="#ecebeb"
>
    <Circle cx="31" cy="586" r="15" />
    <Rect x="65" y="571" rx="2" ry="2" width="140" height="10" /> 
    <Circle cx="204" cy="153" r="45" />
    <Rect x="91" y="227" rx="8" ry="8" width="225" height="23" />
    <Rect x="111" y="255" rx="8" ry="8" width="86" height="48" />
    <Rect x="47" y="338" rx="8" ry="8" width="317" height="13" />
    <Rect x="47" y="430" rx="8" ry="8" width="81" height="13" />
    <Rect x="170" y="430" rx="8" ry="8" width="81" height="13" />
    <Rect x="20" y="624" rx="8" ry="8" width="320" height="10" />
    <Rect x="-20" y="0" rx="15" ry="15" width="500" height="142" />
  </ContentLoader>
);

### Which versions of react-content-loader, and which browser are affected by this issue?
Please also mention the version of react.
Using the latest one

**Comment by hotgeart** [comment]
This doesn't help you: https://github.com/danilowoz/react-content-loader#responsive---mobile-version ?

**Comment by danilowoz** [comment]
Hey, thanks for coming up this issue.

Here's a possible way to solve it, let me know if it works for you:

```jsx
import React from "react";
import { SafeAreaView, StyleSheet, View } from "react-native";

import ContentLoader, { Rect } from "react-content-loader/native";

// viewBox width / viewBox height
const ASPECT_RATIO = 300 / 70;

const MyLoader = () => (
  <ContentLoader height="100%" width="100%" viewBox="0 0 380 70">
    <Rect x="0" y="0" rx="5" ry="5" width="70" height="70" />
    <Rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
    <Rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
  </ContentLoader>
);

export default function App() {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.small}>
        <MyLoader />
      </View>
      <View style={styles.haft}>
        <MyLoader />
      </View>
      <View style={styles.full}>
        <MyLoader />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: "column",
    justifyContent: "flex-start",
    flex: 1,
  },
  small: {
    aspectRatio: ASPECT_RATIO,
    width: "20%",
  },
  haft: {
    aspectRatio: ASPECT_RATIO,
    width: "50%",
  },
  full: {
    aspectRatio: ASPECT_RATIO,
    width: "100%",
  },
});

```

**Comment by TNBoiBoi** [comment]
> Hey, thanks for coming up this issue.
> 
> Here's a possible way to solve it, let me know if it works for you:
> 
> ```js-jsx
> import React from "react";
> import { SafeAreaView, StyleSheet, View } from "react-native";
> 
> import ContentLoader, { Rect } from "react-content-loader/native";
> 
> // viewBox width / viewBox height
> const ASPECT_RATIO = 300 / 70;
> 
> const MyLoader = () => (
>   <ContentLoader height="100%" width="100%" viewBox="0 0 380 70">
>     <Rect x="0" y="0" rx="5" ry="5" width="70" height="70" />
>     <Rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
>     <Rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
>   </ContentLoader>
> );
> 
> export default function App() {
>   return (
>     <SafeAreaView style={styles.container}>
>       <View style={styles.small}>
>         <MyLoader />
>       </View>
>       <View style={styles.haft}>
>         <MyLoader />
>       </View>
>       <View style={styles.full}>
>         <MyLoader />
>       </View>
>     </SafeAreaView>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flexDirection: "column",
>     justifyContent: "flex-start",
>     flex: 1,
>   },
>   small: {
>     aspectRatio: ASPECT_RATIO,
>     width: "20%",
>   },
>   haft: {
>     aspectRatio: ASPECT_RATIO,
>     width: "50%",
>   },
>   full: {
>     aspectRatio: ASPECT_RATIO,
>     width: "100%",
>   },
> });
> ```

Hi Danilo yes it did help and it worked wonderfully !! 
Thanks a lot for the help and for this amazing package 💯
