### ISSUE TITLE
can't enter online tool

### ISSUE THREAD

**Issue by Nfinding** [danilowoz/react-content-loader#249]
### please provide the new online tool address
https://skeletonreact.com/ and https://skeletonreact.com/ don‘t work now

**Comment by danilowoz** [comment]
Can you check it out again? This is working here

**Comment by Nfinding** [comment]
check it out the whole afternoon，but always prompt me ‘https://skeletonreact.com/ web page may be temporarily unable to connect, or it has permanently moved to a new url.’ 
and i checked that is nothing wrong with my mac‘s network proxy
