### ISSUE TITLE
Align rectangles to right side

### ISSUE THREAD

**Issue by MaratEldarov** [danilowoz/react-content-loader#250]
## What did you do? 
Hi! I got this loader:

```
<ContentLoader 
    speed={2}
    width={"100%"}
    height={80}
    viewBox="0 0 400 80"
    backgroundColor="#f3f3f3"
    foregroundColor="#e9ecf2"
    {...props}
  >
    <circle cx="47" cy="38" r="24" /> 
    <rect x="89" y="19" rx="1" ry="1" width="176" height="18" /> 
    <rect x="89" y="45" rx="1" ry="1" width="152" height="14" /> 
    <rect x="277" y="19" rx="1" ry="1" width="74" height="18" /> 
    <rect x="289" y="45" rx="1" ry="1" width="62" height="14" />
  </ContentLoader>
```

## What did you expect to happen?
I need to align my last two rects to right side, so it stays on the right side when ContentLoader width changes. Is it possible?

### Which versions of react-content-loader, and which browser are affected by this issue?
react version 16.2

**Comment by danilowoz** [comment]
Hey!
I don't think it's possible, as far as I know how an SVG works it doesn't seem that you dynamically align an element without affecting the rest of the canvas. 

So my suggestion is to create two different `<ContentLoader />`: one align to the left and another one aligned to right. Which would work properly, but the animation wouldn't be synchronized. 

Hope it helps :)
