### ISSUE TITLE
Unable to loop content loader, possible issue?

### ISSUE THREAD

**Issue by P0SEID0N** [danilowoz/react-content-loader#254]
## What did you do? 
Unable to loop the content loader. 

Basically in react native I was attempting to loop the content loader or a Rect element inside the content loader n amount of times for the sake of use on multiple screens that require different number of loading indicators. 

For example some of the app I have loads the data from the backend in pieces, one of the pieces that loads before the content renders (by design) and I get an N component for the amount of items per page that will be rendered eventually in my list element. I would like to have N amount of loaders to match what the user will see on the page (for transitional value this will essentially give the feeling of lazy loading to the user who is seeing the content load) 

Note: This is in no way a breaking issue. I can work around this I would just like to know if this is possible.

When actually doing the loop like so: 

Note: This is also wrapped in a containg element which might be causing the big box ie the <></>
```
{[...Array(n)].map((e, i) => {
   <>
     <Rect x="333" y={start*i} rx="5" ry="5" width="44" height={h} /> 
     <Rect x="5" y={start*i} rx="5" ry="5" width="315" height={h} />
   </>
})}
```

or I have also tried looping the entire content loader:

```
{[...Array(n)].map((e, i) => {
      <ContentLoader 
      backgroundColor="#c4c4c4"
      foregroundColor="#ebebeb"
      style={{marginLeft: 15, marginRight: 10, flex:1, marginTop: 10}}>
        <Rect x="333" y={start*i} rx="5" ry="5" width="44" height={h} /> 
        <Rect x="5" y={start*i} rx="5" ry="5" width="315" height={h} />
     </ContentLoader>

})}
```

What ends up happening is one large box instead of separate rects. Note: The above code is just an example.

## What did you expect to happen?
I was hoping upon implementation that the Rects could render from the start position to the start position * n times and fill the page with the appropriate loaders.

## What happened actually?
A huge box was created instead of N smaller more defined boxes

### Which versions of react-content-loader, and which browser are affected by this issue?
"react": "16.13.1","react-content-loader": "^6.0.3"

This is on react native.

Thanks for any assistance you guys can provide!! again not a breaking issue just want to know if its possible.

**Comment by danilowoz** [comment]
Hey @P0SEID0N! Yeah, it's possible, and I have a perfect example of how you could do it: https://github.com/danilowoz/create-content-loader/blob/master/src/Gallery/insertYourLoaderHere/RepeatableTableRows.js#L9-L14

```jsx
// 1. Height must dynamic 
<ContentLoader viewBox={`0 0 1500 ${rowHeight * rows}`} {...props}>
      // 2. Loop for a number of time
      {new Array(rows).fill(' ').map((el, index) => {
        // 3. Calc its position
        const contentVerticalPosition = contentHeight =>
          rows > 1 ? contentHeight + rowHeight * index : contentHeight
      
        return (
         // Wrap everything in a Fragment with its proper key
          <Fragment key={index}>
```

Of course that this example is not in React Native, but it's totally possible.
