### ISSUE TITLE
Inferring Dimensions

### ISSUE THREAD

**Issue by MadsFrost** [danilowoz/react-content-loader#262]
I was hoping there was a fix to infer to the dimensions of for example a typography element. But cannot seem to find any method of getting the correct width and height that the ContentLoader should be to load different sizes of text.

Any ideas :)?

**Comment by danilowoz** [comment]
Hey @MadsFrost, so sorry to hear you're facing such an issue.
Could you please paste here the snippet of what you're trying to do? And what is the visual result you want?

Thanks

**Comment by MadsFrost** [comment]
I made a custom component for text, which just wraps any component with some default styles, forgive my awful recreation/explanation, but I want to somehow adapt the width and height to the size of that text, right now it's static:
```
<div>
      <ContentLoader style={{ marginBottom: 5 }} width={'100%'} height={'20'}>
        <rect x='0' y='0' rx='9' ry='15' width={'100%'} height={'20'} />
      </ContentLoader>
</div>
```
This loader is replaced with my Text element while it's loading. A better example is how MUI-UI handles this problem:
https://mui.com/components/skeleton/#inferring-dimensions

Is there any equivalent using React Content Loader :)?

I'm quite new to content loaders as well as TypeScript, but I am sure there must be somewhat of an already made example of this I can't find using React Content Loader.

**Comment by danilowoz** [comment]
Hey @MadsFrost, here's an example of a responsive component: https://codesandbox.io/s/responsive-bf9qr
An SVG element needs a `viewBox` attribute to understand its ratio, and it should do the trick.

Unfortunately, `rect` doesn't support percentage values, so my suggestion is to use specific units (px) and then resize the SVG element with its proper `viewBox`.

Hope it solves your issue :D
