### ISSUE TITLE
RN: ContentLoader backgroundColor and foregroundColor not working with PlatformColor

### ISSUE THREAD

**Issue by 0rsa** [danilowoz/react-content-loader#265]
Hi,

I use RN 0.66.1 with PlatformColor with is useful to use new Android 12 theme colors.
https://reactnative.dev/docs/platformcolor

For example to style an icon with a system accent color, in style attribute:
`color: PlatformColor('@android:color/system_accent2_600'),`

As ContentLoader uses backgroundColor and foregroundColor as properties, PlatformColor color is not resolved and this error displays at runtime:
`WARN  "[object Object]" is not a valid color or "0" is not a valid offset`

Can you handle this type of colors?

Thank you

**Comment by danilowoz** [comment]
Hey @0rsa, thanks for raising this issue, very interesting!
As I write, the React Native documentation is down, so I'm not able to check how PlatformColor is implemented. But the only reason why it doesn't work is that the SVG component doesn't accept other values except for the hexadecimal. So I'm wondering, isn't there any way to convert PlatformColor values to hex? 

Curious to hear your thoughts

**Comment by 0rsa** [comment]
Your component is not the single affected component, I think this is a hard limitation from using PlatformColor.
I use now https://github.com/Assembless/react-native-material-you to get system accent colors as hex.
Problem is solved :-)
