### ISSUE TITLE
seem to not work on stroke base svg

### ISSUE THREAD

**Issue by Sovai** [danilowoz/react-content-loader#284]
I have this svg

` 
<ContentLoader
      width="260"
      height="260"
      viewBox="0 0 300 300"
      class="donut st-margin-32-top"
      primary-color="rgba(255,255,255, 0.3)"
      secondary-color="rgba(255,255,255, 0.5)"
    >
      <circle
        class="donut-segment"
        cx="150"
        cy="150"
        r="130"
        fill="transparent"
        stroke="rgba(255,255,255, 0.5)"
        stroke-width="30"
        stroke-dasharray="608 10"
        stroke-dashoffset="0"
        stroke-linecap="butt"
      ></circle>
      <line
        x1="110"
        y1="155"
        x2="190"
        y2="155"
        stroke="rgba(255,255,255, 0.5)"
        stroke-linecap="round"
        stroke-width="11"
      ></line>
      <line
        x1="100"
        y1="180"
        x2="200"
        y2="180"
        stroke="rgba(255,255,255, 0.5)"
        stroke-linecap="round"
        stroke-width="15"
      ></line>
    </ContentLoader>`

My expected result is the SVG with loading flash animation
![image](https://user-images.githubusercontent.com/8064796/158337773-2e414deb-391a-4a90-a12e-0d3e5c7624fb.png)

But this is what I got
![image](https://user-images.githubusercontent.com/8064796/158337860-3c5311a0-fde5-4b8b-9118-365b42b879eb.png)

Is there no way it support stroke?

**Comment by danilowoz** [comment]
I believe it's a limitation from SVG-mask, so I'd encourage you to use SVG paths elements to draw your loading. Importing & transforming your SVG here (https://skeletonreact.com/) will probably fix this issue for you.

Hope it helps
