### ISSUE TITLE
Improve props to the wrap

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/react-content-loader#29]
- [x] Classnames
- [x] SVG width and height

Maybe I should set all props that component will receive, like `{...props}`

**Comment by bkniffler** [comment]
Please! So depressing that I can't pass a className or inline styles :( Great lib whatsoever, keep it up!

**Comment by bkniffler** [comment]
Oh, and please don't set inline styles by default, it overwrites any css i pass it (except for !important)

**Comment by danilowoz** [comment]
@bkniffler Sorry guy! I didn't notice that :(
But I already updated this, could you look the #38 ?

**Comment by danilowoz** [comment]
@bkniffler I merged it :)
