### ISSUE TITLE
SVG: Support for defaultProps will be removed from function components

### ISSUE THREAD

**Issue by ahmedyounes** [danilowoz/react-content-loader#298]
react-content-loader 6.0.2
react 18.2.0

receiving this

Warning: SVG: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead

**Comment by FaridSafi** [comment]
+1

**Comment by shehi** [comment]
+1 same here. Apparently https://github.com/danilowoz/react-content-loader/blob/master/src/web/Svg.tsx#L117 is the cause.
