### ISSUE TITLE
Skeletons animations are not working in the latest Chrome version

### ISSUE THREAD

**Issue by varayoudfederico** [danilowoz/react-content-loader#316]
## What did you do? 

Opened the examples page: https://skeletonreact.com/#gallery in Chome latest version (122.0.6261.58).

## What did you expect to happen?

The skeletons animate correctly.

## What happened actually?

The skeletons are not animating, they remain static.

### Which versions of react-content-loader, and which browser are affected by this issue?

Locally we use React 18.2.0 and version 6.2.1 of the library. But the issue can be replicated in the examples page.

**Comment by dakioso** [comment]
Same here! And i'm running on a bit newer Chrome version: 122.0.6261.69

**Comment by azzinijuli** [comment]
I'm having the same issue with Chrome v 122.0.6261.70

**Comment by ekkotest** [comment]
me too

**Comment by Cow258** [comment]
I got same issue on Chrome 122.0.6261.69 (arm64)


## Chrome 122.0.6261.69 (arm64)
![image](https://github.com/danilowoz/react-content-loader/assets/14261588/73196927-1a50-4d44-9dfe-51f1839f75c8)

## Safari  17.3.1（19617.2.4.11.12）
![image](https://github.com/danilowoz/react-content-loader/assets/14261588/dab6e8a0-cedf-4d11-b496-b90cebe5542e)

**Comment by GauthierWillemse** [comment]
+1

**Comment by jwebbvalent** [comment]
+1

**Comment by Roeefl** [comment]
We're having the same issue on Brave since updating from v1.62 to v1.63 (Released Feb 28, 2024), which includes chromium upgrade to 122.0.6261.94

**Comment by jabranrafique** [comment]
Not animating for me on MS Edge Version 122.0.2365.59

**Comment by shimi-kuperli** [comment]
+1

**Comment by Roeefl** [comment]
Stupid David Bokan and his Chromium changes

https://chromium.googlesource.com/chromium/src/+/a1f3b8804d221a3c503224c6b558eb19df29e9a0

**Comment by Roeefl** [comment]
@danilowoz We've tried to figure this out and indeed this seems to be a breaking change in Chromium regrading animations for linear-gradients only (I think).

For the meanwhile, we've cloned the `Svg.tsx` file from your repo (thank you!) and simplified it to have it's opacity animated rather than a gradient, just to keep our Production content loaders giving a loading indication.

If this might help you in any way, this is our forked file:
https://gist.github.com/Roeefl/af6e9192aee30c4c120101b70f7f8837

**Comment by danilowoz** [comment]
I think I've found an alternative! Is someone up to review and look for inconsistency? 
I'm pretty sure we will end up deprecating some props, btw
