### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by rodcope1** [danilowoz/react-content-loader#33]
Currently getting multiple deprecation warnings from React 15 and can't use it at all with React 16:

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

**Comment by danilowoz** [comment]
Hey @rodcope1, what version are you using? 
This warning is strange because I've already tested on React 16 and for example, I am not using `PropTypes` but `Flowtypes`
