### ISSUE TITLE
Why save-dev?

### ISSUE THREAD

**Issue by Geczy** [danilowoz/react-content-loader#39]
Why do you recommend saving it as a dev dependency? Isn't it required if you're using it in your prod app to be in your dep's?

**Comment by danilowoz** [comment]
Hey @Geczy, I made a mistake it isn't a dev dependencies
Feel free to open a PR if you want 😄

**Comment by munizart** [comment]
@Geczy thanks to pointing this out! I made a PR and the readme was updated. 
Happy coding. =]
