### ISSUE TITLE
Suggestion to another component

### ISSUE THREAD

**Issue by rricardi** [danilowoz/react-content-loader#5]
I suggest you create a component that imitate the graphic loader  :boy:

**Comment by moimikey** [comment]
spinner loaders have such infinite options. i feel like it wouldn't fit the repo too well. what about a specific shape?

**Comment by borisrorsvort** [comment]
What about map component?

**Comment by danilowoz** [comment]
@moimikey I think the spinners loaders has a another function, which is different from this package that try to simulate the content that will be load. To resolve the problem about the infinitys variations the graphs, I/we can to build a custom element with free path, but I don't know the complexity level to do it. What do you think? @rricardi challenge accepted?

@borisrorsvort I have not thought of this component, I will to study a layout to do this or if you want, feel free to open a PR 😄

**Comment by sompylasar** [comment]
RE: appealing modern spinners, https://github.com/epicmaxco/epic-spinners/issues/1 – no React version yet but they look very nice. _disclaimer: i'm not affiliated_

![epic-spinners](https://user-images.githubusercontent.com/498274/34309060-ebdddc98-e704-11e7-8226-e33dde428122.gif)

**Comment by danilowoz** [comment]
Hey @sompylasar, thanks for your suggestion, but as I already explained above I think the spinners loaders have a different function. React-content-loader tries to simulate the content that will be load to just avoid the spinners. 

Thanks :)

**Comment by sompylasar** [comment]
@danilowoz I didn't mean to suggest extending this package, just wanted to link aspiring contributors to existing work that can be extended to support React.
