### ISSUE TITLE
React-Native Support

### ISSUE THREAD

**Issue by Jose4gg** [danilowoz/react-content-loader#6]
Will you release this to RN?

**Comment by virusvn** [comment]
@Jose4gg 
I've just released a version for React Native at [here] (https://www.npmjs.com/package/react-native-svg-animated-linear-gradient) based on this repo, thanks to @danilowoz. 
Feel free to drop me a line.

**Comment by danilowoz** [comment]
@virusvn It is very cool!
As soon as I have more knowledge abrout Native, I'll contribute!

Thanks for your work!
