### ISSUE TITLE
Why React 16?

### ISSUE THREAD

**Issue by vfonic** [danilowoz/react-content-loader#64]
Hi!

I just installed and tried out `react-content-loader` and it seems to be working great, even though, I have an app that uses React 15. I can't update because I have some packages in my project that are incompatible with React 16.

What's the exact functionality that is dependent on React 16 and not React 15? What's the latest version that supports React 15?

Thanks!

EDIT: I believe changing dependency requirements from react 15 to react 16 is a breaking change. If you're following semver, you should release new major version.

**Comment by vfonic** [comment]
I just wanted to submit a PR to backport `className` prop to latest react 15 supported version of the package. However, latest react 15 supported version is 1.6.0, while, patch version bump to 1.6.1, was the update of dependencies to react 16. I suggest creating react 15 compatible 1.6.2 version and maybe also releasing 2.0.0 (or keep 1.7.x, but that's not really following semver) for react 16.

**Comment by danilowoz** [comment]
Hey there!
I was really worried about the compatibility with old React versions, but I forgot to work on this, sorry man!

I'm releasing a new Major version with a lot of changes and improvements and I tested these changes using the React 15 and I didn't have any problem. 

Could you please update it to 2.0.0 and feedback me if everything happens right? 

Thanks :)

**Comment by vfonic** [comment]
Everything seems to be working fine. Thanks!
