### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by lasseborly** [danilowoz/react-content-loader#7]
Hi, I really like your lib.

Are you still interested in making the List component?
I would gladly open a PR and work on it and at the same time get my SVG muscles worked out a bit.

**Comment by danilowoz** [comment]
Hi @lasseborly!
Feel free for make this component, you can open a PR or if you have a specific question, you can to ask me 😄

**Comment by lasseborly** [comment]
Ok @danilowoz.

So I took a very KISS approach, looked at the components and came up with this for a list component?

![list](https://user-images.githubusercontent.com/2671660/27755571-c67ef04c-5df0-11e7-94e5-57aa0547910e.png)

Comments? The code is ready to be submitted as a PR, but before pushing it through I just wanted some feedback :fire:

**Comment by danilowoz** [comment]
@lasseborly nice!
I think it's ok, please open the PR and then we can to add one more component!

Thanks

**Comment by lasseborly** [comment]
Nice. Will do.
