### ISSUE TITLE
Suggestion: Issue and pull request templates

### ISSUE THREAD

**Issue by munizart** [danilowoz/react-content-loader#73]
Wouldn't it be nice to have [templates](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) for issues and pull requests for this repository?

I had scratched this yet for PRs:
```markdown
Fix issue #[issue number].

Changes proposed by this pull request:
- Change 1
- Change 2
- Change 3

@[reviewer] and @[another reviewer], could you please review this PR?

Checklist:
- [x] Used template
- [ ] Described proposed changes
- [ ] Marked at least two reviewers
- [ ] Wrote tests
```

I think it would be nice to discuss the template and what is missing in the checklist.
Also, it would be great to have an contributing guide.

@danilowoz, any thoughts on that?

**Comment by danilowoz** [comment]
Sounds great! 

But not all pull request will be about issues/fixes. It can be a new feature, improvements, etc.  Maybe you just need to improve the title, you know? 
And you can add a new section, asking if the change is a "breaking change" or not? 

What do you think?
Thanks

Greeting, xaropês

**Comment by danilowoz** [comment]
Nice!
I'm waiting for you PR :)

**Comment by danilowoz** [comment]
Hey @munizart, how are doing? 
So, would you like to keep this issue with you? Or can I open the community to make it?
I think it is a great improvement and I want to solve that :)

Thanks

**Comment by munizart** [comment]
@danilowoz sorry, right now I can't make it. But it would be great if someone could take it from here
🦄
