### ISSUE TITLE
Suggestion: handle animation

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/react-content-loader#77]
It would be interesting if the package had an animation control. To remove the SVG animations tags and any extra code. So, there are two ways: 

## prop animation
Like `<ContentLoader animation={false} />`

## speed 0
If speed is zero||null, remove the animation tags;

**Comment by caian-gums** [comment]
Solve this on #80 PR

**Comment by Turkyden** [comment]
i love your code, guy.

**Comment by AjayPoshak** [comment]
Oh! I am late.
Still, I have made changes, please take a look. [PR#82](https://github.com/danilowoz/react-content-loader/pull/82)
