### ISSUE TITLE
Add "esnext" field in package.json

### ISSUE THREAD

**Issue by Alex-Ferreli** [danilowoz/react-content-loader#8]
Hi, thanks for the awesome package!

Could you add the esnext field on package.json to point src directory please? So webpack can do tree shaking on the src directory.

Thanks.

EDIT: sorry the field name is "jsnext:main" ("module" also work).

**Comment by danilowoz** [comment]
Hi @Alex-Ferreli! Can you leave a example how I do this?
I didn't understand exactly how I should to do it.

**Comment by Alex-Ferreli** [comment]
Hi @danilowoz. Webpack has a feature called tree-shaking (https://webpack.js.org/guides/tree-shaking/) but to work need that the loaded module use ES2015 import/export syntax. You are serving to webpack the index.js file wich point to the compiled bundle.

Webpack can read a special field in the package.json called "jsnext:main" ("module" also work). This filed must point to the src file that use import/export.

See d3 package.json: https://github.com/d3/d3/blob/master/package.json
