### ISSUE TITLE
Not working in Safari.

### ISSUE THREAD

**Issue by Ekluv** [danilowoz/react-content-loader#93]
## What did you do? 
My Loader Component 

```
const Loader = props => (
  <ContentLoader
    preserveAspectRatio="none"
    style={{width: '100%' }}
  >
    <rect x="0" y="0" rx="5" ry="5" width="100%" height={300} /> 
  </ContentLoader>
)
```

## What did you expect to happen?
Expect to work for all browsers

## What happened actually?
Working fine on Chrome and FireFox but giving black layout for safari.
![image](https://user-images.githubusercontent.com/11562881/39406054-2f308de6-4bce-11e8-91fb-bbb35e29fc10.png)

### Which versions of react-content-loader, and which browser are affected by this issue?
`"react-content-loader": "^3.1.1"`
`"react": "^15.4.2"`
Browsers: Safari

**Comment by danilowoz** [comment]
Hey @Ekluv, thanks for the report
I got some tests here and it works fine:
![screen shot 2018-04-29 at 12 23 02](https://user-images.githubusercontent.com/4838076/39408247-b72b0c32-4ba9-11e8-802d-030a5a7fe7d0.png)

First, what is the version of Safari? And are there some styles in the parents? 
Try to isolate the component and let me know if that works

Thanks

**Comment by karanmartian** [comment]
same. I get black screen content when viewed on mobile with all browsers. I am rendering the content loader inside a custom card component

**Comment by danilowoz** [comment]
@karanmartian @Ekluv let me know which browser version you are using, please
I have been testing on safari/iOS 10 and other browser and it works fine 

<img width="432" alt="screen shot 2018-05-02 at 08 52 00" src="https://user-images.githubusercontent.com/4838076/39521817-87c55076-4de6-11e8-9a0f-a608705bd613.png">

**Comment by karanmartian** [comment]
iOS ver 11.3 Safari and also Chrome. 
It works fine on Desktop browsers. But on mobile it shows black content

**Comment by danilowoz** [comment]
hey, I invited you to talk more about it here: https://gitter.im/react-content-loader/Lobby#

**Comment by Ekluv** [comment]
@danilowoz only style i have used is flex. check screenshot

![image](https://user-images.githubusercontent.com/11562881/39540377-195d431c-4e60-11e8-87b9-99e0731f44e9.png)

Target: Safari Version 11.0.3

**Comment by danilowoz** [comment]
@Ekluv @karanmartian 
Can you try to isolate the code in a sandbox? Because of I couldn't see the bug yet, so if you paste the code enough to see the bug I will try to investigate again. 

So far I just can conclude that is Safari bug (as @samwalshnz already mentioned).
If you have more information, please reopen the PR

Thank so much for your contributions

**Comment by samwalshnz** [comment]
My PR proposes the use of `primaryOpacity` and `secondaryOpacity` so that it can work in Safari. Basically, instead of using rgba values for primary/secondaryColor, switch it to rgb and move the alpha value from the rgba color to the new primary/secondaryOpacity props. Described in more detail in the updated Readme.md and commit messages etc

**Comment by danilowoz** [comment]
I just published these changes on v3.1.2 👍

**Comment by yogeshk1990** [comment]
I tried all your methods, Its not working

**Comment by danilowoz** [comment]
Hey @yogeshk1990 
Do you have any other information so I can help you?

Which version of browser are you using? Are you using the latest version of the package? Can you the code in the codesandbox that reproduces the bug?

**Comment by pzmuda13** [comment]
Hi, I am develooing angular app using port for angular of this lib. I have simmilar problem and i discovered that's it only occurs in paths different than main page '/' 

More description:
https://github.com/NetanelBasal/ngx-content-loader/issues/23

Maybe this scenario also applies to your lib?

**Comment by danilowoz** [comment]
**Hey guys, I found a answer:**

## Problem:

> HTML <base> element is used to say "resolve all relative URLs relative not to this page, but to a new location". In your case, you've told it to resolve relative to the directory with the HTML page.
https://stackoverflow.com/questions/18259032/using-base-tag-on-a-page-that-contains-svg-marker-elements-fails-to-render-marke/18265336#18265336

## Solution

**Remove `<base href="/">` from the document**
https://github.com/airbnb/lottie-web/issues/360

Actually there is another way to solve it. But currently, there is no way to customize the `url()` in the svg, even using the `uniquekey` prop. I'll document it and I'll try to figure out a better workaround.
https://github.com/airbnb/lottie-web/issues/360#issuecomment-320243980

Besides that, let me know if it works, thanks

**Safari,** welcome to new IE

**Comment by pzmuda13** [comment]
After removing base href angular libs works too, thanks @danilowoz  :)

**Comment by majid-amiri** [comment]
Hi,
I am using version ^4.0.1 and I have this problem on Safari both on Mac and iOS. I know that removing `<base />` is a solution to this issue but I need the `<base />` tag in my app and I can't remove it. Do you have any other solutions for this issue?

**Comment by danilowoz** [comment]
@majid-amiri please update to latest version take a look at this solution:

**`baseUrl? string`**
Required if you're using `<base url="/" />` in your `<head/>`. Defaults to an empty string. This prop is common used as: `<ContentLoader baseUrl={window.location.pathname} />` which will fill the SVG attribute with the relative path. 

Let me know if it works

**Comment by andelizondo** [comment]
`<ContentLoader baseUrl={window.location.pathname} />` 

That fixed the issue for me, as I also needed the `<base href="/">` tag in my app.
Thank you @danilowoz! 🎉

**Comment by phatNfqAsia** [comment]
@danilowoz 
I upgraded to the 4.2.1 and did as instructed. I have one skeleton component applied to two different pages but only one of them worked. 
Just so you know that the new update does not solve the issue completely, while removing the
<base href /> in <head> is more radical

**Comment by danilowoz** [comment]
Hey there, could you please send me a codesandbox? 
Then I can debug what's happening 

Thanks

**Comment by yohanessahrul** [comment]
in my chrome not work, but safari perfectly

**Comment by danilowoz** [comment]
Hey @yohanessahrul, can you send more details?
I would like to know how I could solve this issue, probably there are more people with this problem

Thanks

**Comment by jakhongir-i** [comment]
doesn’t work in safari, everything is fine in chrome



![screen](https://user-images.githubusercontent.com/46269246/77226057-079a2e00-6b97-11ea-947d-3c99ffab72da.jpg)

**Comment by vanoMekantsishvili** [comment]
I've decide to use Svg files, I draw in playground but on safari it shows black screen (But not always, though). Any suggestions? Or I need to actually install content-loader package and use < <ContentLoader /> ?

**Comment by vanoMekantsishvili** [comment]
Turned out if you attach unique ids for 'clip-path' and 'fill' it works ^_^ at least on version Safari 12.1.2

**Comment by CatchGus** [comment]
I was also witnessing this black box issue on Safari even though we have no `<base />` tag. For me the solution was to exclude `ContentLoader` being rendered server side.
