### ISSUE TITLE
Webpack unable to bundle style file 'styles-compiled.css'

### ISSUE THREAD

**Issue by pndirpaya** [danilowoz/react-content-loader#95]
i tried importing the CSS styles-compiled.css file into a react app, and i got an error from webpack. while trying to bundle the app

i expected the css file to be loaded for the Card component, rather i got the following error: 

```js

bundle.js:3676 ./~/react-credit-cards/es/styles-compiled.css
Module parse failed: ~/node_modules/react-credit-cards/es/styles-compiled.css Unexpected token (3:0)
You may need an appropriate loader to handle this file type.
| /** ISSUERS **/
| /** Images **/
| .rccs {
|   margin: 0 auto;
|   -webkit-perspective: 1000px;
 @ ./src/components/Forms/AddCardForm.js 28:0-74
 @ ./src/screens/Payments.js
 @ ./src/App.js
 @ multi (webpack)-dev-server/client?http://localhost:4172 babel-polyfill ./src/App.js


```

react version : 16.3.1

**Comment by pndirpaya** [comment]
@danilowoz a thousand apologies. i posted an issue meant for another repo here. 🤦🏾‍♂️

thank you for an amazing content loader, i had fun creating custom content loaders. 

once again my sincere apologies.

**Comment by danilowoz** [comment]
Thanks and no problem 🍻
