### ISSUE TITLE
Help: I can't figure out how to use it properly?

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [danilowoz/react-content-loader#97]
I am unable to use it, I mean I want to cover all my page, but it's actually showing only at specific area of my react component, can you help me with some demo code please?

**Comment by danilowoz** [comment]
I'm not sure how I can help you. Have you built a component using the loader? 
If not, I can build a sandbox with loader, using a delay from fake API and show you how that works.

Maybe it can help you, take a look at the top of the page:
http://danilowoz.com/create-content-loader/

Let me know, how I can help you

**Comment by kashifullahwebdeveloper** [comment]
No, I haven't as I am a newbie in react, can you please make a sandbox with fake API call that would be really helpful.

Thank you for your amazing plugin!

**Comment by danilowoz** [comment]
Hey @kashifullahwebdeveloper 
Take a look [here](https://codesandbox.io/embed/j4zmn07oow)

Did it help you?
