### ISSUE TITLE
[Suggestion] Nested placeholder

### ISSUE THREAD

**Issue by CosticaPuntaru** [danilowoz/react-content-loader#99]
i want to build a board with cards, 
it will be nice if i can create a placeholder for Board, placeholder for Column and a placeholder for Card reusing the placeholder for card,
allowing me to reuse placeholders, and allowing the creation of dynamic columns and cards

expected usage: 
``` javascript

function Column(){} // simple square
function Card(){} // a card placeholder

function Board({columnArray}){
   return (
      <ContentLoader>
        {columnArray.map(() => {
            return ( 
              <Column>
                   {Array(5).map(() => {
                     return (<Card/>);
                    )}
              </Column>
            );
        });}
      </ContentLoader>
  );
} 
 
```

**Comment by danilowoz** [comment]
@CosticaPuntaru sorry for the delay
Actually, you already can do that, take a look at https://codesandbox.io/s/3v2xoj6v25
